### ISSUE TITLE
OutPut Game Crash

### ISSUE THREAD

**Issue by rub432** [SanAndreasP/ClaySoldiersMod#101]
When I press play in the minecraft laucher, it will load but not compleatly, under Game Output it appears this:
[12:50:40] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[12:50:40] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[12:50:40] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[12:50:40] [main/INFO] [FML]: Forge Mod Loader version 8.99.18.1419 for Minecraft 1.8 loading
[12:50:40] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_25, running on Windows 8.1:amd64:6.3, installed at C:\Users\Jack\Desktop\LEL Games\runtime\jre-x64\1.8.0_25
[12:50:40] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.NoClassDefFoundError: cpw/mods/fml/relauncher/IFMLLoadingPlugin
[12:50:40] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.ClassLoader.defineClass1(Native Method)
[12:50:40] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
[12:50:40] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[12:50:40] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:455)
[12:50:40] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
[12:50:40] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.net.URLClassLoader$1.run(URLClassLoader.java:367)
[12:50:40] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
[12:50:40] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.security.AccessController.doPrivileged(Native Method)
[12:50:40] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
[12:50:40] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117)
[12:50:40] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[12:50:40] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[12:50:40] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.Class.forName0(Native Method)
[12:50:40] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.Class.forName(Class.java:344)
[12:50:40] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:447)
[12:50:40] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:371)
[12:50:40] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:239)
[12:50:40] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90)
[12:50:40] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67)
[12:50:40] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34)
[12:50:40] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraftforge.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126)
[12:50:40] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[12:50:40] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[12:50:40] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: java.lang.ClassNotFoundException: cpw.mods.fml.relauncher.IFMLLoadingPlugin
[12:50:40] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[12:50:40] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[12:50:40] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[12:50:40] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	... 23 more
[12:50:40] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: java.lang.NullPointerException
[12:50:40] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
[12:50:40] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	... 25 more
[12:50:40] [main/ERROR] [FML]: An error occurred trying to configure the minecraft home at C:\Users\Jack\AppData\Roaming\.minecraft for Forge Mod Loader
java.lang.NoClassDefFoundError: cpw/mods/fml/relauncher/IFMLLoadingPlugin
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_25]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760) ~[?:1.8.0_25]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_25]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:455) ~[?:1.8.0_25]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[?:1.8.0_25]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:367) ~[?:1.8.0_25]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[?:1.8.0_25]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_25]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_25]
	at java.lang.Class.forName(Class.java:344) ~[?:1.8.0_25]
	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:447) ~[forge-1.8-11.14.1.1419.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:371) ~[forge-1.8-11.14.1.1419.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:239) ~[forge-1.8-11.14.1.1419.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90) [forge-1.8-11.14.1.1419.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67) [forge-1.8-11.14.1.1419.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34) [forge-1.8-11.14.1.1419.jar:?]
	at net.minecraftforge.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126) [forge-1.8-11.14.1.1419.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
Caused by: java.lang.ClassNotFoundException: cpw.mods.fml.relauncher.IFMLLoadingPlugin
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
	... 23 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
	... 23 more
Exception in thread "main" [12:50:40] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.NoClassDefFoundError: cpw/mods/fml/relauncher/IFMLLoadingPlugin
[12:50:40] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.ClassLoader.defineClass1(Native Method)
[12:50:40] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
[12:50:40] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[12:50:40] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:455)
[12:50:40] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
[12:50:40] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.net.URLClassLoader$1.run(URLClassLoader.java:367)
[12:50:40] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
[12:50:40] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.security.AccessController.doPrivileged(Native Method)
[12:50:40] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
[12:50:40] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117)
[12:50:40] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[12:50:40] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[12:50:40] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.Class.forName0(Native Method)
[12:50:40] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.Class.forName(Class.java:344)
[12:50:40] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:447)
[12:50:40] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:371)
[12:50:40] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:239)
[12:50:40] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90)
[12:50:40] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67)
[12:50:40] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34)
[12:50:40] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraftforge.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126)
[12:50:40] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[12:50:40] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[12:50:40] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: java.lang.ClassNotFoundException: cpw.mods.fml.relauncher.IFMLLoadingPlugin
[12:50:40] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[12:50:40] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[12:50:40] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[12:50:40] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	... 23 more
[12:50:40] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: java.lang.NullPointerException
[12:50:40] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
[12:50:40] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	... 25 more

Please do help

**Comment by SanAndreasP** [comment]
The mod is not out for Minecraft 1.8. Use 1.7.10 for now.
