### ISSUE TITLE
Right clicking on nexus results in game crash.(with something in hand)

### ISSUE THREAD

**Issue by Nukemaker** [SanAndreasP/ClaySoldiersMod#139]
Here is the crash report:
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 10/10/15 1:19 AM
Description: Unexpected error

java.lang.NoClassDefFoundError: de/sanandrew/core/manpack/util/client/SAPClientUtils
    at de.sanandrew.mods.claysoldiers.client.event.RenderStatDisplayOverlay.renderSoldiers(RenderStatDisplayOverlay.java:91)
    at de.sanandrew.mods.claysoldiers.client.event.RenderStatDisplayOverlay.renderText(RenderStatDisplayOverlay.java:64)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_41_RenderStatDisplayOverlay_renderText_Text.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
    at net.minecraftforge.client.GuiIngameForge.renderHUDText(GuiIngameForge.java:699)
    at net.minecraftforge.client.GuiIngameForge.func_73830_a(GuiIngameForge.java:155)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1038)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:989)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: de.sanandrew.core.manpack.util.client.SAPClientUtils
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 17 more
Caused by: java.lang.NullPointerException
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
    ... 19 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at de.sanandrew.mods.claysoldiers.client.event.RenderStatDisplayOverlay.renderSoldiers(RenderStatDisplayOverlay.java:91)
    at de.sanandrew.mods.claysoldiers.client.event.RenderStatDisplayOverlay.renderText(RenderStatDisplayOverlay.java:64)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_41_RenderStatDisplayOverlay_renderText_Text.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
    at net.minecraftforge.client.GuiIngameForge.renderHUDText(GuiIngameForge.java:699)
    at net.minecraftforge.client.GuiIngameForge.func_73830_a(GuiIngameForge.java:155)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityClientPlayerMP['Nukemaker'/53, l='MpServer', x=212.92, y=5.62, z=-164.39]]
    Chunk stats: MultiplayerChunkCache: 624, 624
    Level seed: 0
    Level generator: ID 01 - flat, ver 0. Features enabled: false
    Level generator options: 
    Level spawn location: World: (366,4,-90), Chunk: (at 14,0,6 in 22,-6; contains blocks 352,0,-96 to 367,255,-81), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
    Level time: 2614 game time, 2614 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 19 total; [EntityHuman['Lyra the Mason'/13, l='MpServer', x=165.50, y=4.00, z=-199.47], EntitySheep['Sheep'/65586, l='MpServer', x=218.50, y=4.00, z=-218.50], EntitySheep['Sheep'/65587, l='MpServer', x=217.50, y=4.00, z=-216.50], EntitySheep['Sheep'/65584, l='MpServer', x=224.50, y=4.00, z=-217.50], EntitySheep['Sheep'/65585, l='MpServer', x=221.50, y=4.00, z=-221.50], EntitySheep['Sheep'/65590, l='MpServer', x=215.91, y=4.00, z=-222.50], EntitySheep['Sheep'/65591, l='MpServer', x=207.22, y=4.00, z=-230.31], EntitySheep['Sheep'/65588, l='MpServer', x=210.03, y=4.00, z=-213.94], EntitySheep['Sheep'/65589, l='MpServer', x=217.22, y=4.00, z=-222.69], EntityClientPlayerMP['Nukemaker'/53, l='MpServer', x=212.92, y=5.62, z=-164.39], EntityCow['Cow'/65583, l='MpServer', x=223.50, y=4.00, z=-213.50], EntityCow['Cow'/65582, l='MpServer', x=225.50, y=4.00, z=-215.50], EntityCow['Cow'/65581, l='MpServer', x=222.50, y=4.00, z=-219.50], EntityCow['Cow'/65580, l='MpServer', x=222.50, y=4.00, z=-216.50], EntityCow['Cow'/65624, l='MpServer', x=215.50, y=4.00, z=-85.50], EntityCow['Cow'/65625, l='MpServer', x=217.50, y=4.00, z=-85.50], EntityHuman['Cam the Weaponsmith'/62804, l='MpServer', x=164.61, y=4.00, z=-192.38], EntityHuman['Daire the Fisherman'/62810, l='MpServer', x=164.69, y=4.00, z=-194.44], EntityHuman['Zed the Butcher'/43522, l='MpServer', x=164.41, y=4.00, z=-206.16]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2432)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:916)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.7.0_71, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 897633976 bytes (856 MB) / 1056309248 bytes (1007 MB) up to 1593180160 bytes (1519 MB)
    JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -XX:-OmitStackTraceInFastThrow -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xms1024M -Xmx1536M -XX:PermSize=256M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 8 mods loaded, 8 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FML{7.10.85.1291} [Forge Mod Loader](forge-1.7.10-10.13.2.1291-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forge{10.13.2.1291} [Minecraft Forge](forge-1.7.10-10.13.2.1291-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    sapmanpack{2.5.1} [SanAndreasPs Manager Pack CORE edition](SAPManPack-1.7.10-2.5.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    claysoldiers{2.0.0b} [Clay Soldiers Mod](Clay-Soldiers-Mod-1.7.10.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    RadixCore{2.0.2} [RadixCore](RadixCore-2.0.2-1.7.10-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MCA{5.0.6} [Minecraft Comes Alive](MCA-5.0.6-1.7.10-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    WebDisplay{0.10} [Web Displays](WebDisplays-0.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Launched Version: 1.7.10
    LWJGL: 2.9.1
    OpenGL: GeForce 8400GS/PCI/SSE2 GL version 3.3.0, NVIDIA Corporation
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

```
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: []
Current Language: English (US)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: Off (1)
```

Please Help!

**Comment by Spartan322** [comment]
please use gist or pastebin next time, also could you tell use what item(s) you had in hand, that would be very helpful.

**Comment by Nukemaker** [comment]
i was holding a clay man specify 1 blue clay soldier (i also did it with red and the normal grey)

**Comment by MBTshock** [comment]
You are not supposed to see this :)

**Comment by SanAndreasP** [comment]
I'll now close most issues in here for now, since I need to recode everything again for 1.10 / 1.11 anyway.
