### ISSUE TITLE
Not compatible with DragonAPI

### ISSUE THREAD

**Issue by LutherX** [SanAndreasP/ClaySoldiersMod#158]
Using Ars Magica it loads fine, as soon as I install DragonAPI the game crashes on load with the following error.  Without DragonAPI, Clay Soldiers loads fine.

[spoiler]
java.lang.IllegalArgumentException: resource AM2_at.cfg not found.
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:148) ~[guava-17.0.jar:?]
	at com.google.common.io.Resources.getResource(Resources.java:229) ~[guava-17.0.jar:?]
	at cpw.mods.fml.common.asm.transformers.AccessTransformer.readMapFile(AccessTransformer.java:118) ~[forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.common.asm.transformers.AccessTransformer.<init>(AccessTransformer.java:101) ~[forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at am2.preloader.AccessTransformers.<init>(AccessTransformers.java:10) ~[AccessTransformers.class:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_25]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408) ~[?:1.8.0_25]
	at java.lang.Class.newInstance(Class.java:438) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.LaunchClassLoader.registerTransformer(LaunchClassLoader.java:88) [launchwrapper-1.12.jar:?]
	at cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:108) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[11:46:46] [main/INFO] [ArsMagica2]: Core: Located DragonAPI in DragonAPI 1.7.10 V12e.jar
[11:46:46] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[11:46:46] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[11:46:46] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[11:46:46] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[11:46:46] [main/INFO] [LaunchWrapper]: Calling tweak class forestry.shade.javacheck.Java7Checker
[11:46:46] [main/INFO] [LaunchWrapper]: Calling tweak class me.guichaguri.betterfps.tweaker.BetterFpsTweaker
[11:46:46] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLDeobfTweaker
[11:46:46] [main/ERROR] [LaunchWrapper]: A critical problem occurred registering the ASM transformer class 
java.lang.ClassNotFoundException: 
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.LaunchClassLoader.registerTransformer(LaunchClassLoader.java:88) [launchwrapper-1.12.jar:?]
	at cpw.mods.fml.common.launcher.FMLDeobfTweaker.injectIntoClassLoader(FMLDeobfTweaker.java:32) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 6
	at org.objectweb.asm.ClassReader.readShort(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
	at org.objectweb.asm.ClassReader.<init>(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
	at org.objectweb.asm.ClassReader.<init>(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
	at cpw.mods.fml.common.asm.transformers.DeobfuscationTransformer.transform(DeobfuscationTransformer.java:34) ~[forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	... 6 more
[/spoiler]

**Comment by LutherX** [comment]
Think I posted too early. Not sure it's an issue with Clay Soldiers.

**Comment by Bogdan-G** [comment]
>java.lang.IllegalArgumentException: resource AM2_at.cfg not found.

game should not fall with this error
