### ISSUE TITLE
---- Minecraft Crash Report ----

### ISSUE THREAD

**Issue by ltvman** [SanAndreasP/ClaySoldiersMod#162]
Time: 6/9/16 2:09 PM
Description: Rendering entity in world

java.lang.NoClassDefFoundError: de/sanandrew/core/manpack/util/client/ItemRenderHelper
	at de.sanandrew.mods.claysoldiers.client.event.SoldierLeftHandRenderHandler.renderShield(SoldierLeftHandRenderHandler.java:83)
	at de.sanandrew.mods.claysoldiers.client.event.SoldierLeftHandRenderHandler.onSoldierRender(SoldierLeftHandRenderHandler.java:47)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_20_SoldierLeftHandRenderHandler_onSoldierRender_SoldierRenderEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at de.sanandrew.mods.claysoldiers.client.render.entity.RenderClayMan.func_77029_c(RenderClayMan.java:55)
	at net.minecraft.client.renderer.entity.RendererLivingEntity.func_76986_a(RendererLivingEntity.java:213)
	at net.minecraft.client.renderer.entity.RenderLiving.func_76986_a(SourceFile:23)
	at net.minecraft.client.renderer.entity.RenderBiped.func_76986_a(RenderBiped.java:164)
	at de.sanandrew.mods.claysoldiers.client.render.entity.RenderClayMan.doRenderClayMan(RenderClayMan.java:84)
	at de.sanandrew.mods.claysoldiers.client.render.entity.RenderClayMan.func_76986_a(RenderClayMan.java:44)
	at net.minecraft.client.renderer.entity.RenderBiped.func_76986_a(RenderBiped.java:361)
	at net.minecraft.client.renderer.entity.RenderManager.func_147939_a(RenderManager.java:293)
	at net.minecraft.client.renderer.entity.RenderManager.func_147936_a(RenderManager.java:271)
	at net.minecraft.client.renderer.entity.RenderManager.func_147937_a(RenderManager.java:244)
	at net.minecraft.client.renderer.RenderGlobal.func_147589_a(RenderGlobal.java:471)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1224)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1015)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: de.sanandrew.core.manpack.util.client.ItemRenderHelper
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 27 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 29 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at de.sanandrew.mods.claysoldiers.client.event.SoldierLeftHandRenderHandler.renderShield(SoldierLeftHandRenderHandler.java:83)
	at de.sanandrew.mods.claysoldiers.client.event.SoldierLeftHandRenderHandler.onSoldierRender(SoldierLeftHandRenderHandler.java:47)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_20_SoldierLeftHandRenderHandler_onSoldierRender_SoldierRenderEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at de.sanandrew.mods.claysoldiers.client.render.entity.RenderClayMan.func_77029_c(RenderClayMan.java:55)
	at net.minecraft.client.renderer.entity.RendererLivingEntity.func_76986_a(RendererLivingEntity.java:213)
	at net.minecraft.client.renderer.entity.RenderLiving.func_76986_a(SourceFile:23)
	at net.minecraft.client.renderer.entity.RenderBiped.func_76986_a(RenderBiped.java:164)
	at de.sanandrew.mods.claysoldiers.client.render.entity.RenderClayMan.doRenderClayMan(RenderClayMan.java:84)
	at de.sanandrew.mods.claysoldiers.client.render.entity.RenderClayMan.func_76986_a(RenderClayMan.java:44)
	at net.minecraft.client.renderer.entity.RenderBiped.func_76986_a(RenderBiped.java:361)

-- Entity being rendered --
Details:
	Entity Type: claysoldiers.clayman (de.sanandrew.mods.claysoldiers.entity.EntityClayMan)
	Entity ID: 1138246
	Entity Name: entity.claysoldiers.clayman.name
	Entity's Exact location: -150.52, 4.00, 384.92
	Entity's Block location: World: (-151,4,384), Chunk: (at 9,0,0 in -10,24; contains blocks -160,0,384 to -145,255,399), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00

-- Renderer details --
Details:
	Assigned renderer: de.sanandrew.mods.claysoldiers.client.render.entity.RenderClayMan@18ab9b9e
	Location: 0.02,-3.62,-1.12 - World: (0,-4,-2), Chunk: (at 0,-1,14 in 0,-1; contains blocks 0,0,-16 to 15,255,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Rotation: 163.85417
	Delta: 0.14238
Stacktrace:
	at net.minecraft.client.renderer.entity.RenderManager.func_147939_a(RenderManager.java:293)
	at net.minecraft.client.renderer.entity.RenderManager.func_147936_a(RenderManager.java:271)
	at net.minecraft.client.renderer.entity.RenderManager.func_147937_a(RenderManager.java:244)
	at net.minecraft.client.renderer.RenderGlobal.func_147589_a(RenderGlobal.java:471)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1224)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['Ian_Montgomery'/0, l='MpServer', x=-150.53, y=7.62, z=386.11]]
	Chunk stats: MultiplayerChunkCache: 623, 623
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-95,4,351), Chunk: (at 1,0,15 in -6,21; contains blocks -96,0,336 to -81,255,351), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 11694 game time, 11694 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 83 total; [EntityClayMan['entity.claysoldiers.clayman.name'/1611928, l='MpServer', x=-148.81, y=4.00, z=386.19], EntityItem['item.item.egg'/1943583, l='MpServer', x=-109.53, y=4.13, z=390.41], EntityClayMan['entity.claysoldiers.clayman.name'/552448, l='MpServer', x=-151.25, y=4.00, z=389.28], EntityItem['item.item.egg'/1404703, l='MpServer', x=-168.06, y=4.13, z=420.84], EntityItem['item.item.egg'/1621387, l='MpServer', x=-151.78, y=4.13, z=359.69], EntityCow['Cow'/67223, l='MpServer', x=-222.50, y=4.00, z=389.50], EntityCow['Cow'/67225, l='MpServer', x=-219.50, y=4.00, z=395.81], EntityCow['Cow'/67224, l='MpServer', x=-219.50, y=4.00, z=394.22], EntityCow['Cow'/67226, l='MpServer', x=-220.50, y=4.00, z=397.50], EntityChicken['Chicken'/67229, l='MpServer', x=-226.50, y=4.00, z=387.50], EntityChicken['Chicken'/67103, l='MpServer', x=-160.38, y=4.00, z=354.56], EntityChicken['Chicken'/67231, l='MpServer', x=-221.50, y=4.00, z=388.50], EntityChicken['Chicken'/67230, l='MpServer', x=-228.50, y=4.00, z=386.50], EntityChicken['Chicken'/67105, l='MpServer', x=-107.56, y=4.00, z=390.47], EntityChicken['Chicken'/67233, l='MpServer', x=-222.50, y=4.00, z=384.50], EntityChicken['Chicken'/67104, l='MpServer', x=-128.77, y=4.00, z=362.11], EntityChicken['Chicken'/67232, l='MpServer', x=-219.50, y=4.00, z=386.50], EntityPig['Pig'/67107, l='MpServer', x=-98.28, y=4.00, z=381.97], EntityPig['Pig'/67235, l='MpServer', x=-155.50, y=4.00, z=427.63], EntityChicken['Chicken'/67106, l='MpServer', x=-116.53, y=4.00, z=378.56], EntityChicken['Chicken'/67234, l='MpServer', x=-226.50, y=4.00, z=383.50], EntityPig['Pig'/67109, l='MpServer', x=-116.22, y=4.00, z=375.28], EntityPig['Pig'/67237, l='MpServer', x=-154.59, y=4.00, z=423.81], EntityPig['Pig'/67108, l='MpServer', x=-114.75, y=4.00, z=376.16], EntityClayMan['entity.claysoldiers.clayman.name'/1143732, l='MpServer', x=-148.47, y=4.00, z=388.44], EntityPig['Pig'/67111, l='MpServer', x=-96.84, y=4.00, z=381.94], EntityChicken['Chicken'/67239, l='MpServer', x=-169.38, y=4.00, z=421.59], EntityPig['Pig'/67110, l='MpServer', x=-102.50, y=4.00, z=380.50], EntityPig['Pig'/67238, l='MpServer', x=-147.97, y=4.00, z=420.91], EntityItem['item.item.egg'/1537456, l='MpServer', x=-124.69, y=4.13, z=367.44], EntityPig['Pig'/67113, l='MpServer', x=-108.28, y=4.00, z=378.91], EntityChicken['Chicken'/67241, l='MpServer', x=-157.50, y=4.00, z=426.50], EntityClientPlayerMP['Ian_Montgomery'/0, l='MpServer', x=-150.53, y=7.62, z=386.11], EntityPig['Pig'/67112, l='MpServer', x=-116.97, y=4.00, z=402.09], EntityChicken['Chicken'/67240, l='MpServer', x=-156.50, y=4.00, z=426.50], EntitySheep['Sheep'/67243, l='MpServer', x=-153.69, y=4.00, z=428.78], EntityClayMan['entity.claysoldiers.clayman.name'/1135675, l='MpServer', x=-152.50, y=4.00, z=386.50], EntityPig['Pig'/67114, l='MpServer', x=-96.03, y=4.00, z=370.94], EntityChicken['Chicken'/67242, l='MpServer', x=-154.25, y=4.00, z=422.94], EntitySheep['Sheep'/67244, l='MpServer', x=-157.59, y=4.00, z=425.59], EntitySheep['Sheep'/67246, l='MpServer', x=-188.75, y=4.00, z=390.63], EntityItem['item.item.egg'/1416634, l='MpServer', x=-116.69, y=4.13, z=380.66], EntityItem['item.item.egg'/1708068, l='MpServer', x=-159.81, y=4.13, z=426.25], EntityCow['Cow'/67139, l='MpServer', x=-112.22, y=4.00, z=310.22], EntityCow['Cow'/67141, l='MpServer', x=-112.50, y=4.00, z=313.50], EntityCow['Cow'/67140, l='MpServer', x=-113.81, y=4.00, z=311.81], EntityChicken['Chicken'/67143, l='MpServer', x=-107.50, y=4.00, z=311.50], EntityCow['Cow'/67142, l='MpServer', x=-108.50, y=4.00, z=313.50], EntityChicken['Chicken'/67145, l='MpServer', x=-104.50, y=4.00, z=308.34], EntityChicken['Chicken'/67144, l='MpServer', x=-103.50, y=4.00, z=312.50], EntityHorse['Horse'/67147, l='MpServer', x=-107.03, y=4.00, z=309.97], EntityClayMan['entity.claysoldiers.clayman.name'/1126618, l='MpServer', x=-152.50, y=4.00, z=388.50], EntityChicken['Chicken'/67146, l='MpServer', x=-105.53, y=4.00, z=305.47], EntityHorse['Horse'/67149, l='MpServer', x=-105.03, y=4.00, z=309.47], EntitySheep['Sheep'/67151, l='MpServer', x=-74.50, y=4.00, z=451.50], EntitySheep['Sheep'/67153, l='MpServer', x=-73.66, y=4.00, z=456.06], EntityPig['Pig'/67155, l='MpServer', x=-78.50, y=4.00, z=453.50], EntitySheep['Sheep'/67154, l='MpServer', x=-72.50, y=4.00, z=457.50], EntityPig['Pig'/67157, l='MpServer', x=-74.38, y=4.00, z=449.84], EntityPig['Pig'/67156, l='MpServer', x=-76.63, y=4.00, z=450.38], EntityClayMan['entity.claysoldiers.clayman.name'/1138246, l='MpServer', x=-150.52, y=4.00, z=384.92], EntityPig['Pig'/67158, l='MpServer', x=-73.91, y=4.00, z=454.75], EntityChicken['Chicken'/67161, l='MpServer', x=-78.50, y=4.00, z=462.50], EntityChicken['Chicken'/67160, l='MpServer', x=-77.50, y=4.00, z=460.50], EntityChicken['Chicken'/67162, l='MpServer', x=-75.50, y=4.00, z=463.50], EntityChicken['Chicken'/67165, l='MpServer', x=-75.53, y=4.00, z=379.59], EntityChicken['Chicken'/67164, l='MpServer', x=-75.50, y=4.00, z=382.50], EntityChicken['Chicken'/67167, l='MpServer', x=-75.50, y=4.00, z=386.50], EntityChicken['Chicken'/67166, l='MpServer', x=-77.50, y=4.00, z=380.50], EntityChicken['Chicken'/67168, l='MpServer', x=-80.44, y=4.00, z=387.53], EntityChicken['Chicken'/67171, l='MpServer', x=-73.50, y=4.00, z=387.50], EntityItem['item.item.egg'/1471732, l='MpServer', x=-154.91, y=4.13, z=425.09], EntityChicken['Chicken'/67170, l='MpServer', x=-78.97, y=4.00, z=388.69], EntityChicken['Chicken'/67173, l='MpServer', x=-81.47, y=4.00, z=399.47], EntityChicken['Chicken'/67172, l='MpServer', x=-86.38, y=4.00, z=391.44], EntityChicken['Chicken'/67174, l='MpServer', x=-74.50, y=4.00, z=387.50], EntityCow['Cow'/67193, l='MpServer', x=-77.50, y=4.00, z=457.50], EntityCow['Cow'/67192, l='MpServer', x=-73.03, y=4.00, z=452.97], EntityItem['item.item.egg'/1855846, l='MpServer', x=-158.41, y=4.13, z=426.28], EntityCow['Cow'/67194, l='MpServer', x=-79.50, y=4.00, z=461.50], EntityPig['Pig'/67197, l='MpServer', x=-73.78, y=4.00, z=445.78], EntityPig['Pig'/67196, l='MpServer', x=-73.50, y=4.00, z=441.50], EntityPig['Pig'/67198, l='MpServer', x=-72.19, y=4.00, z=444.19]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 92884928 bytes (88 MB) / 323551232 bytes (308 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1481 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1481-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1481} [Minecraft Forge] (forge-1.7.10-10.13.4.1481-1.7.10.jar) 
	UCHIJAAAA	sapmanpack{2.5.1} [SanAndreasPs Manager Pack CORE edition] (SAPManPack-1.7.10-2.5.1.jar) 
	UCHIJAAAA	claysoldiers{2.0.0b} [Clay Soldiers Mod] (Clay-Soldiers-Mod-1.7.10.zip) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 359.00' Renderer: 'GeForce GTX 570/PCIe/SSE2'
	Launched Version: 1.7.10-Forge10.13.4.1481-1.7.10
	LWJGL: 2.9.1
	OpenGL: GeForce GTX 570/PCIe/SSE2 GL version 4.5.0 NVIDIA 359.00, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by SanAndreasP** [comment]
You seem to use beta 1. Use the latest beta 2.
