### ISSUE TITLE
PLEASE HELP!!!! CRASHING!!!

### ISSUE THREAD

**Issue by Purpledot27** [SanAndreasP/ClaySoldiersMod#168]
---- Minecraft Crash Report ----
// On the bright side, I bought you a teddy bear!

Time: 7/5/16 9:50 PM
Description: Updating screen events

java.lang.ArrayIndexOutOfBoundsException: -1
	at net.minecraft.item.ItemStack.func_77980_a(ItemStack.java:386)
	at net.minecraft.inventory.SlotCrafting.func_75208_c(SlotCrafting.java:53)
	at net.minecraft.inventory.SlotCrafting.func_82870_a(SlotCrafting.java:110)
	at net.minecraft.inventory.Container.func_75144_a(SourceFile:238)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78753_a(PlayerControllerMP.java:419)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146984_a(GuiContainer.java:641)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:394)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.item.ItemStack.func_77980_a(ItemStack.java:386)
	at net.minecraft.inventory.SlotCrafting.func_75208_c(SlotCrafting.java:53)
	at net.minecraft.inventory.SlotCrafting.func_82870_a(SlotCrafting.java:110)
	at net.minecraft.inventory.Container.func_75144_a(SourceFile:238)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78753_a(PlayerControllerMP.java:419)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146984_a(GuiContainer.java:641)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:394)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)

-- Affected screen --
Details:
	Screen name: net.minecraft.client.gui.inventory.GuiCrafting

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['purpledot27'/2934, l='MpServer', x=-2.89, y=67.62, z=-1.33]]
	Chunk stats: MultiplayerChunkCache: 409, 409
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,64,0), Chunk: (at 0,4,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 24991 game time, 24991 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 104 total; [EntityClientPlayerMP['purpledot27'/2934, l='MpServer', x=-2.89, y=67.62, z=-1.33], EntitySkeleton['Skeleton'/3584, l='MpServer', x=36.50, y=40.00, z=-1.50], EntityCreeper['Creeper'/2563, l='MpServer', x=4.00, y=50.00, z=-9.41], EntityBat['Bat'/2567, l='MpServer', x=0.28, y=42.10, z=-6.13], EntityZombie['Zombie'/3853, l='MpServer', x=-63.50, y=32.00, z=-61.09], EntitySkeleton['Skeleton'/2578, l='MpServer', x=22.50, y=33.00, z=27.50], EntityZombie['Zombie'/3859, l='MpServer', x=-37.50, y=38.00, z=-62.50], EntityCreeper['Creeper'/3351, l='MpServer', x=-15.50, y=30.00, z=-13.50], EntityZombie['Zombie'/3609, l='MpServer', x=21.50, y=37.00, z=24.50], EntityZombie['Zombie'/3612, l='MpServer', x=8.69, y=13.00, z=47.69], EntitySpider['Spider'/3874, l='MpServer', x=52.88, y=50.00, z=-29.66], EntitySkeleton['Skeleton'/3875, l='MpServer', x=64.50, y=50.00, z=-38.50], EntityZombie['Zombie'/3621, l='MpServer', x=73.50, y=14.00, z=-64.50], EntityZombie['Zombie'/3624, l='MpServer', x=74.50, y=14.00, z=-60.50], EntityZombie['Zombie'/2858, l='MpServer', x=-9.94, y=34.00, z=15.44], EntityZombie['Zombie'/3372, l='MpServer', x=-57.94, y=31.00, z=-69.50], EntityCreeper['Creeper'/2861, l='MpServer', x=-23.85, y=44.00, z=-0.06], EntitySpider['Spider'/3376, l='MpServer', x=-6.56, y=15.06, z=40.00], EntitySkeleton['Skeleton'/3890, l='MpServer', x=25.50, y=29.00, z=21.50], EntitySkeleton['Skeleton'/3891, l='MpServer', x=25.50, y=29.00, z=20.50], EntitySkeleton['Skeleton'/3892, l='MpServer', x=23.50, y=29.00, z=20.50], EntitySkeleton['Skeleton'/3126, l='MpServer', x=21.97, y=37.00, z=-6.56], EntityZombie['Zombie'/3127, l='MpServer', x=2.69, y=49.00, z=-10.25], EntitySkeleton['Skeleton'/3639, l='MpServer', x=-7.50, y=21.00, z=-1.50], EntityCreeper['Creeper'/3896, l='MpServer', x=31.41, y=14.00, z=20.06], EntitySkeleton['Skeleton'/3385, l='MpServer', x=-60.50, y=30.00, z=-5.50], EntityCreeper['Creeper'/3897, l='MpServer', x=27.50, y=13.00, z=11.50], EntityZombie['Zombie'/3898, l='MpServer', x=19.47, y=13.00, z=10.31], EntityZombie['Zombie'/3899, l='MpServer', x=19.59, y=13.00, z=11.16], EntitySkeleton['Skeleton'/3645, l='MpServer', x=48.50, y=19.00, z=49.50], EntitySkeleton['Skeleton'/3649, l='MpServer', x=21.50, y=54.00, z=-27.50], EntitySkeleton['Skeleton'/3661, l='MpServer', x=2.50, y=16.00, z=-12.50], EntityZombie['Zombie'/3920, l='MpServer', x=7.50, y=31.00, z=-3.50], EntityZombie['Zombie'/3921, l='MpServer', x=-2.03, y=30.00, z=-6.47], EntityZombie['Zombie'/3922, l='MpServer', x=3.31, y=31.00, z=-3.31], EntityZombie['Zombie'/3668, l='MpServer', x=8.50, y=13.00, z=44.50], EntityCreeper['Creeper'/3925, l='MpServer', x=-26.50, y=32.00, z=-15.50], EntityBat['Bat'/3414, l='MpServer', x=23.25, y=38.10, z=-22.25], EntitySquid['Squid'/2903, l='MpServer', x=-65.50, y=53.00, z=-18.50], EntityCreeper['Creeper'/3928, l='MpServer', x=-3.50, y=43.00, z=-12.50], EntityZombie['Zombie'/3929, l='MpServer', x=-5.50, y=43.00, z=-11.50], EntityZombie['Zombie'/3930, l='MpServer', x=-49.50, y=62.00, z=-60.50], EntityZombie['Zombie'/3423, l='MpServer', x=-21.50, y=24.00, z=-26.50], EntityZombie['Zombie'/3687, l='MpServer', x=-1.03, y=39.00, z=21.53], EntitySpider['Spider'/3693, l='MpServer', x=33.88, y=15.00, z=20.38], EntityBat['Bat'/3184, l='MpServer', x=24.50, y=34.10, z=-70.25], EntitySquid['Squid'/3698, l='MpServer', x=-5.44, y=62.38, z=55.81], EntityBat['Bat'/3444, l='MpServer', x=-36.66, y=31.60, z=-50.97], EntitySquid['Squid'/3700, l='MpServer', x=-2.81, y=62.22, z=56.06], EntityItem['item.item.dyePowder.black'/2933, l='MpServer', x=26.19, y=47.13, z=-24.69], EntityCreeper['Creeper'/3957, l='MpServer', x=-32.50, y=14.00, z=-64.50], EntityZombie['Zombie'/3958, l='MpServer', x=-31.50, y=14.00, z=-66.50], EntityCreeper['Creeper'/3959, l='MpServer', x=-32.50, y=14.00, z=-63.50], EntityCreeper['Creeper'/3707, l='MpServer', x=49.50, y=36.00, z=-69.50], EntityBat['Bat'/3452, l='MpServer', x=-13.88, y=32.64, z=-8.88], EntityCreeper['Creeper'/3710, l='MpServer', x=75.50, y=16.00, z=-64.50], EntitySkeleton['Skeleton'/3712, l='MpServer', x=18.50, y=43.00, z=-2.09], EntityBat['Bat'/3457, l='MpServer', x=-35.31, y=25.10, z=-21.50], EntityBat['Bat'/3458, l='MpServer', x=-4.25, y=25.10, z=-28.75], EntityBat['Bat'/3461, l='MpServer', x=-12.72, y=33.00, z=-1.28], EntityBat['Bat'/3464, l='MpServer', x=17.75, y=28.10, z=8.75], EntityCreeper['Creeper'/3722, l='MpServer', x=-45.50, y=33.00, z=-64.50], EntityBat['Bat'/3985, l='MpServer', x=18.75, y=35.52, z=31.23], EntityBat['Bat'/3987, l='MpServer', x=2.56, y=33.94, z=42.77], EntityBat['Bat'/3988, l='MpServer', x=27.10, y=50.81, z=-2.08], EntityBat['Bat'/3989, l='MpServer', x=22.31, y=50.93, z=1.90], EntityBat['Bat'/3990, l='MpServer', x=29.28, y=50.24, z=-3.99], EntityCreeper['Creeper'/3737, l='MpServer', x=-44.50, y=33.00, z=-56.50], EntityBat['Bat'/3993, l='MpServer', x=-25.90, y=58.84, z=-22.09], EntitySkeleton['Skeleton'/3738, l='MpServer', x=-47.69, y=57.00, z=-4.72], EntityBat['Bat'/3994, l='MpServer', x=-25.33, y=59.82, z=-12.35], EntityZombie['Zombie'/3739, l='MpServer', x=-50.50, y=55.00, z=-10.50], EntityBat['Bat'/3998, l='MpServer', x=-25.08, y=59.00, z=-10.09], EntityCreeper['Creeper'/2981, l='MpServer', x=-10.22, y=34.00, z=0.84], EntityCreeper['Creeper'/2982, l='MpServer', x=-23.67, y=43.00, z=1.07], EntitySkeleton['Skeleton'/3240, l='MpServer', x=55.50, y=66.00, z=11.50], EntityBat['Bat'/3754, l='MpServer', x=-3.88, y=14.12, z=39.50], EntityCreeper['Creeper'/3761, l='MpServer', x=-59.50, y=23.00, z=-63.50], EntityCreeper['Creeper'/3252, l='MpServer', x=18.50, y=25.00, z=8.50], EntitySquid['Squid'/3508, l='MpServer', x=-66.75, y=54.34, z=-18.09], EntityWitch['Witch'/3764, l='MpServer', x=-30.13, y=18.00, z=28.47], EntitySkeleton['Skeleton'/3767, l='MpServer', x=7.50, y=37.00, z=-11.50], EntitySkeleton['Skeleton'/3771, l='MpServer', x=0.50, y=36.00, z=3.50], EntitySkeleton['Skeleton'/3772, l='MpServer', x=-1.69, y=36.00, z=4.63], EntitySpider['Spider'/3517, l='MpServer', x=24.03, y=37.00, z=-8.28], EntitySkeleton['Skeleton'/3773, l='MpServer', x=-5.53, y=34.00, z=3.88], EntitySkeleton['Skeleton'/3774, l='MpServer', x=-3.06, y=36.00, z=1.53], EntityBat['Bat'/3008, l='MpServer', x=-30.19, y=12.69, z=-56.12], EntitySkeleton['Skeleton'/3522, l='MpServer', x=-39.50, y=39.00, z=-53.50], EntityZombie['Zombie'/3524, l='MpServer', x=-35.50, y=22.00, z=-21.50], EntityZombie['Zombie'/3525, l='MpServer', x=-35.50, y=22.00, z=-25.50], EntityBat['Bat'/3787, l='MpServer', x=-34.25, y=23.10, z=-25.25], EntitySkeleton['Skeleton'/2782, l='MpServer', x=11.47, y=46.00, z=13.06], EntitySkeleton['Skeleton'/3040, l='MpServer', x=-0.66, y=48.08, z=-15.50], EntityBat['Bat'/3809, l='MpServer', x=-10.28, y=15.20, z=-34.88], EntityBat['Bat'/3813, l='MpServer', x=-27.50, y=13.76, z=-55.72], EntityBat['Bat'/3814, l='MpServer', x=-26.03, y=17.76, z=-59.28], EntityBat['Bat'/3815, l='MpServer', x=-16.67, y=11.37, z=-69.61], EntitySkeleton['Skeleton'/3825, l='MpServer', x=-77.50, y=39.00, z=78.50], EntityZombie['Zombie'/3834, l='MpServer', x=31.50, y=36.00, z=-31.50], EntitySkeleton['Skeleton'/3323, l='MpServer', x=27.50, y=38.00, z=-5.50], EntityCreeper['Creeper'/3835, l='MpServer', x=-9.50, y=34.00, z=2.50], EntityCreeper['Creeper'/3836, l='MpServer', x=-7.50, y=34.00, z=1.50], EntitySlime['Slime'/3837, l='MpServer', x=-11.63, y=34.00, z=3.63]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 141653536 bytes (135 MB) / 324632576 bytes (309 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJA	sapmanpack{2.5.1} [SanAndreasPs Manager Pack CORE edition] (SAPManPack-1.7.10-2.5.1.jar) 
	UCHIJA	claysoldiers{2.0.0-beta.2} [Clay Soldiers Mod] (ClaySoldiersMod-1.7.10-2.0.0-beta.2.jar) 
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13416 Compatibility Profile Context 15.201.1151.1008' Renderer: 'AMD Radeon HD 6800 Series'
	Launched Version: 1.7.10-Forge10.13.4.1614-1.7.10
	LWJGL: 2.9.1
	OpenGL: AMD Radeon HD 6800 Series GL version 4.5.13416 Compatibility Profile Context 15.201.1151.1008, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

Please help me this is too much for me to do on my own :(

here is the actual crash report if you need it...

[crash-2016-07-05_21.50.14-client.txt](https://github.com/SanAndreasP/ClaySoldiersMod/files/348974/crash-2016-07-05_21.50.14-client.txt)

**Comment by Purpledot27** [comment]
@SanAndreasP  ik you have a lot to do and i appreciate all the help so please try to help asap

**Comment by Purpledot27** [comment]
i figured it all out but thank you!
