### ISSUE TITLE
Minecraft Chrashes when trying to play

### ISSUE THREAD

**Issue by jmanyoyo8080** [SanAndreasP/ClaySoldiersMod#169]
My minecraft crashes when ever I try to play single player or look at my mods and then click done. How am I able to load the mod without minecraft crashing?

Here is my crash report

---- Minecraft Crash Report ----
// Quite honestly, I wouldn't worry myself about that.

Time: 7/6/16 4:19 PM
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at com.arisux.airi.Updater$1.drawWindowContents(Updater.java:141)
	at com.arisux.airi.lib.render.windowapi.themes.Theme.drawContents(Theme.java:49)
	at com.arisux.airi.lib.render.windowapi.themes.Theme.drawWindow(Theme.java:26)
	at com.arisux.airi.lib.render.windowapi.themes.ThemeDefault.drawWindow(ThemeDefault.java:17)
	at com.arisux.airi.lib.windowapi.WindowAPI.drawWindow(WindowAPI.java:54)
	at com.arisux.airi.lib.windowapi.WindowManager.func_73863_a(WindowManager.java:168)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.arisux.airi.Updater$1.drawWindowContents(Updater.java:141)
	at com.arisux.airi.lib.render.windowapi.themes.Theme.drawContents(Theme.java:49)
	at com.arisux.airi.lib.render.windowapi.themes.Theme.drawWindow(Theme.java:26)
	at com.arisux.airi.lib.render.windowapi.themes.ThemeDefault.drawWindow(ThemeDefault.java:17)
	at com.arisux.airi.lib.windowapi.WindowAPI.drawWindow(WindowAPI.java:54)
	at com.arisux.airi.lib.windowapi.WindowManager.func_73863_a(WindowManager.java:168)

-- Screen render details --
Details:
	Screen name: com.arisux.airi.lib.windowapi.WindowManager
	Mouse location: Scaled: (270, 321). Absolute: (541, 62)
	Screen size: Scaled: (683, 353). Absolute: (1366, 705). Scale factor of 2
Stacktrace:
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 115772864 bytes (110 MB) / 281341952 bytes (268 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJA	sapmanpack{2.5.1} [SanAndreasPs Manager Pack CORE edition] (SAPManPack-1.7.10-2.5.1.jar) 
	UCHIJA	AIRI{3.0.0-1.7.10} [AIRI] (AIRI.jar) 
	UCHIJA	AliensVsPredator{3.9.14-1.7.10} [AliensVsPredator] (AliensVsPredator.jar) 
	UCHIJA	claysoldiers{2.0.0-beta.2} [Clay Soldiers Mod] (ClaySoldiersMod-1.7.10-2.0.0-beta.1.jar) 
	GL info: ' Vendor: 'Intel' Version: '4.3.0 - Build 20.19.15.4331' Renderer: 'Intel(R) HD Graphics 4400'
	Launched Version: 1.7.10-Forge10.13.4.1614-1.7.10
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics 4400 GL version 4.3.0 - Build 20.19.15.4331, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by Spartan322** [comment]
You should be blaming AIRI from what I see.
