### ISSUE TITLE
clay soldiers crashes back to launher instantly

### ISSUE THREAD

**Issue by JammerFTW** [SanAndreasP/ClaySoldiersMod#177]
[14:43:04] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/entity/passive/EntityHorse
	at net.minecraft.entity.EntityList.<clinit>(EntityList.java:302) ~[sg.class:?]
	at net.minecraft.item.ItemMonsterPlacer.func_77653_i(SourceFile:34) ~[aee.class:?]
	at net.minecraft.item.ItemStack.func_82833_r(ItemStack.java:427) ~[add.class:?]
	at net.minecraft.item.ItemStack.func_151000_E(ItemStack.java:759) ~[add.class:?]
	at net.minecraft.stats.StatList.func_75925_c(StatList.java:139) ~[pp.class:?]
	at net.minecraft.stats.StatList.func_151178_a(StatList.java:59) ~[pp.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(SourceFile:359) ~[kl.class:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:287) ~[bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:129) ~[Main.class:?]
	... 6 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.entity.passive.EntityHorse
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
	at net.minecraft.entity.EntityList.<clinit>(EntityList.java:302) ~[sg.class:?]
	at net.minecraft.item.ItemMonsterPlacer.func_77653_i(SourceFile:34) ~[aee.class:?]
	at net.minecraft.item.ItemStack.func_82833_r(ItemStack.java:427) ~[add.class:?]
	at net.minecraft.item.ItemStack.func_151000_E(ItemStack.java:759) ~[add.class:?]
	at net.minecraft.stats.StatList.func_75925_c(StatList.java:139) ~[pp.class:?]
	at net.minecraft.stats.StatList.func_151178_a(StatList.java:59) ~[pp.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(SourceFile:359) ~[kl.class:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:287) ~[bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:129) ~[Main.class:?]
	... 6 more
Caused by: de.sanandrew.core.manpack.transformer.ASMHelper$InvalidNeedleException: Multiple Needles found in Haystack!
	at de.sanandrew.core.manpack.transformer.ASMHelper.findFirstNodeFromNeedle(ASMHelper.java:58) ~[SAPManPack-1.7.10-2.5.1.jar:?]
	at de.sanandrew.core.manpack.transformer.TransformHorseArmor.transformUpdateHorseSlots(TransformHorseArmor.java:255) ~[SAPManPack-1.7.10-2.5.1.jar:?]
	at de.sanandrew.core.manpack.transformer.TransformHorseArmor.transformHorse(TransformHorseArmor.java:42) ~[SAPManPack-1.7.10-2.5.1.jar:?]
	at de.sanandrew.core.manpack.transformer.TransformHorseArmor.transform(TransformHorseArmor.java:24) ~[SAPManPack-1.7.10-2.5.1.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
	at net.minecraft.entity.EntityList.<clinit>(EntityList.java:302) ~[sg.class:?]
	at net.minecraft.item.ItemMonsterPlacer.func_77653_i(SourceFile:34) ~[aee.class:?]
	at net.minecraft.item.ItemStack.func_82833_r(ItemStack.java:427) ~[add.class:?]
	at net.minecraft.item.ItemStack.func_151000_E(ItemStack.java:759) ~[add.class:?]
	at net.minecraft.stats.StatList.func_75925_c(StatList.java:139) ~[pp.class:?]
	at net.minecraft.stats.StatList.func_151178_a(StatList.java:59) ~[pp.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(SourceFile:359) ~[kl.class:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:287) ~[bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:129) ~[Main.class:?]
	... 6 more
Exception in thread "main" [14:43:04] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: cpw.mods.fml.relauncher.FMLSecurityManager$ExitTrappedException
[14:43:04] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:25)
[14:43:04] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[14:43:04] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.Runtime.exit(Runtime.java:107)
[14:43:04] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.System.exit(System.java:968)
[14:43:04] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[14:43:04] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

what is this crash and how do i fix it because i really want to use this mod but it does this. Also this is all the launcher outputs when I launch so if you want more well I'm sorry. I don't have more then this. :(

**Comment by SanAndreasP** [comment]
What Minecraft Version?
Do you have a mod called "Bookshelf" installed? If so, the manager pack and that mod are incompatible right now.

**Comment by JammerFTW** [comment]
oh! i have bookshelf installed! that would explain it! and it's fixed! thank you! +1
