### ISSUE TITLE
Minecraft start crash

### ISSUE THREAD

**Issue by aoaguiar** [SanAndreasP/ClaySoldiersMod#182]
I have just upgraded to Minecraft 1.11, but it won't load if clay soldiers and managmenet mods are in the mod folder. No other mods (I removed all other mods to make sure there was no incompatible ones). I did not have clay soldiers mod before, so I am not sure if it is a Minecraft version issue.
The error message is:

2016-11-19 12:36:26,444 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
2016-11-19 12:36:26,446 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
[12:36:26] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[12:36:27] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[12:36:27] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[12:36:28] [main/INFO] [FML]: Forge Mod Loader version 12.18.1.2046 for Minecraft 1.10.2 loading
[12:36:28] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_25, running on Windows 7:amd64:6.1, installed at C:\Program Files (x86)\Minecraft\runtime\jre-x64\1.8.0_25
[12:36:28] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: java.lang.NoClassDefFoundError: cpw/mods/fml/relauncher/IFMLLoadingPlugin
[12:36:28] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: 	at java.lang.ClassLoader.defineClass1(Native Method)
[12:36:28] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: 	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
[12:36:28] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[12:36:28] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:455)
[12:36:28] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: 	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
[12:36:28] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: 	at java.net.URLClassLoader$1.run(URLClassLoader.java:367)
[12:36:28] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: 	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
[12:36:28] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: 	at java.security.AccessController.doPrivileged(Native Method)
[12:36:28] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: 	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
[12:36:28] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117)
[12:36:28] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[12:36:28] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[12:36:28] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: 	at java.lang.Class.forName0(Native Method)
[12:36:28] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: 	at java.lang.Class.forName(Class.java:344)
[12:36:28] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: 	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:552)
[12:36:28] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: 	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:423)
[12:36:28] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: 	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:253)
[12:36:28] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: 	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:102)
[12:36:28] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: 	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:79)
[12:36:28] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: 	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:41)
[12:36:28] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: 	at net.minecraftforge.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:138)
[12:36:28] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[12:36:28] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[12:36:28] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: Caused by: java.lang.ClassNotFoundException: cpw.mods.fml.relauncher.IFMLLoadingPlugin
[12:36:28] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[12:36:28] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[12:36:28] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[12:36:28] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	... 23 more
[12:36:28] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]: Caused by: java.lang.NullPointerException
[12:36:28] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
[12:36:28] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]: 	... 25 more
[12:36:28] [main/ERROR] [FML]: An error occurred trying to configure the minecraft home at C:\Users\André\AppData\Roaming\.minecraft for Forge Mod Loader
java.lang.NoClassDefFoundError: cpw/mods/fml/relauncher/IFMLLoadingPlugin
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_25]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760) ~[?:1.8.0_25]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_25]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:455) ~[?:1.8.0_25]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[?:1.8.0_25]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:367) ~[?:1.8.0_25]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[?:1.8.0_25]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_25]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_25]
	at java.lang.Class.forName(Class.java:344) ~[?:1.8.0_25]
	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:552) ~[forge-1.10.2-12.18.1.2046.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:423) ~[forge-1.10.2-12.18.1.2046.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:253) ~[forge-1.10.2-12.18.1.2046.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:102) [forge-1.10.2-12.18.1.2046.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:79) [forge-1.10.2-12.18.1.2046.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:41) [forge-1.10.2-12.18.1.2046.jar:?]
	at net.minecraftforge.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:138) [forge-1.10.2-12.18.1.2046.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.ClassNotFoundException: cpw.mods.fml.relauncher.IFMLLoadingPlugin
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
	... 23 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
	... 23 more
Exception in thread "main" [12:36:29] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.NoClassDefFoundError: cpw/mods/fml/relauncher/IFMLLoadingPlugin
[12:36:29] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.ClassLoader.defineClass1(Native Method)
[12:36:29] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
[12:36:29] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[12:36:29] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:455)
[12:36:29] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
[12:36:29] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.net.URLClassLoader$1.run(URLClassLoader.java:367)
[12:36:29] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
[12:36:29] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.security.AccessController.doPrivileged(Native Method)
[12:36:29] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
[12:36:29] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117)
[12:36:29] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[12:36:29] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[12:36:29] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Class.forName0(Native Method)
[12:36:29] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Class.forName(Class.java:344)
[12:36:29] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:552)
[12:36:29] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:423)
[12:36:29] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:253)
[12:36:29] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:102)
[12:36:29] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:79)
[12:36:29] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:41)
[12:36:29] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:138)
[12:36:29] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[12:36:29] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[12:36:29] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: Caused by: java.lang.ClassNotFoundException: cpw.mods.fml.relauncher.IFMLLoadingPlugin
[12:36:29] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[12:36:29] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[12:36:29] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[12:36:29] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	... 23 more
[12:36:29] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]: Caused by: java.lang.NullPointerException
[12:36:29] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
[12:36:29] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]: 	... 25 more

**Comment by SanAndreasP** [comment]
The mod is not out for 1.11
