### ISSUE TITLE
crashing on mojang screen ;-;

### ISSUE THREAD

**Issue by jb043** [SanAndreasP/ClaySoldiersMod#193]
Make sure you check following things before you open a new issue:

2017-04-22 09:19:52,670 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
2017-04-22 09:19:52,672 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
[09:19:52] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[09:19:52] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[09:19:52] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[09:19:52] [main/INFO] [FML]: Forge Mod Loader version 12.18.3.2185 for Minecraft 1.10.2 loading
[09:19:52] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_131, running on Windows 7:amd64:6.1, installed at C:\jAVAV
[09:19:53] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[09:19:53] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[09:19:53] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[09:19:53] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[09:19:53] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[09:19:59] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[09:19:59] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[09:19:59] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[09:19:59] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[09:20:02] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[09:20:02] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[09:20:03] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
2017-04-22 09:20:07,110 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
2017-04-22 09:20:08,417 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
2017-04-22 09:20:08,422 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
[09:20:09] [Client thread/INFO]: Setting user: JB043
[09:20:14] [Client thread/WARN]: Skipping bad option: streamPreferredServer:
[09:20:14] [Client thread/INFO]: LWJGL Version: 2.9.4
[09:20:16] [Client thread/INFO] [STDOUT]: [net.minecraftforge.fml.client.SplashProgress:start:219]: ---- Minecraft Crash Report ----
// Sorry :(

Time: 4/22/17 9:20 AM
Description: Loading screen debug info

This is just a prompt for computer specs to be printed. THIS IS NOT A ERROR

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_131, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 162577688 bytes (155 MB) / 306827264 bytes (292 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'Intel' Version: '2.1.0 - Build 8.15.10.1855' Renderer: 'Mobile Intel(R) 4 Series Express Chipset Family'
[09:20:17] [Client thread/INFO] [FML]: MinecraftForge v12.18.3.2185 Initialized
[09:20:17] [Client thread/INFO] [FML]: Replaced 231 ore recipes
[09:20:17] [Client thread/INFO] [FML]: Found 0 mods from the command line. Injecting into mod discoverer
[09:20:17] [Client thread/INFO] [FML]: Searching C:\Users\sample\AppData\Roaming\.minecraft\mods for mods
[09:20:19] [Client thread/INFO] [mercurius_updater]: Mod mercurius_updater is missing the required element 'name'. Substituting mercurius_updater
[09:20:20] [Client thread/INFO] [FML]: Forge Mod Loader has identified 7 mods to load
[09:20:20] [Client thread/INFO] [FML]: Attempting connection with missing mods [mcp, FML, Forge, mercurius_updater, claysoldiers, sanlib, sanplayermodel] at CLIENT
[09:20:20] [Client thread/INFO] [FML]: Attempting connection with missing mods [mcp, FML, Forge, mercurius_updater, claysoldiers, sanlib, sanplayermodel] at SERVER
[09:20:21] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:mercurius_updater, FMLFileResourcePack:Clay Soldiers Mod, FMLFileResourcePack:SanAndreasPs Mod Library, FMLFileResourcePack:SanAndreasPs Player Model
[09:20:21] [Client thread/INFO] [FML]: Processing ObjectHolder annotations
[09:20:21] [Client thread/INFO] [FML]: Found 425 ObjectHolder annotations
[09:20:21] [Client thread/INFO] [FML]: Identifying ItemStackHolder annotations
[09:20:21] [Client thread/INFO] [FML]: Found 0 ItemStackHolder annotations
[09:20:21] [Client thread/INFO] [FML]: Applying holder lookups
[09:20:21] [Client thread/INFO] [FML]: Holder lookups applied
[09:20:21] [Client thread/INFO] [FML]: Applying holder lookups
[09:20:21] [Client thread/INFO] [FML]: Holder lookups applied
[09:20:21] [Client thread/INFO] [FML]: Applying holder lookups
[09:20:21] [Client thread/INFO] [FML]: Holder lookups applied
[09:20:21] [Client thread/INFO] [FML]: Configured a dormant chunk cache size of 0
[09:20:21] [Forge Version Check/INFO] [ForgeVersionCheck]: [Forge] Starting version check at http://files.minecraftforge.net/maven/net/minecraftforge/forge/promotions_slim.json
[09:20:21] [Client thread/INFO] [mercurius]: Version Number exists, Using it: 1.9.4-1.0.4.18
[09:20:21] [Client thread/INFO] [mercurius]: File exists, Checking hash: C:\Users\sample\AppData\Roaming\.minecraft\libraries\net\minecraftforge\Mercurius\1.9.4-1.0.4.18\Mercurius-1.9.4-1.0.4.18.jar
[09:20:21] [Client thread/INFO] [mercurius]:   Hash matches, Skipping download: 50697c062b7698592973d10352ba2566679ed897
[09:20:21] [Client thread/INFO] [mercurius]: Mercurius Jar contains all signed files! Continueing loading!
[09:20:21] [Client thread/INFO] [FML]: Applying holder lookups
[09:20:21] [Client thread/INFO] [FML]: Holder lookups applied
[09:20:21] [Client thread/INFO] [FML]: Injecting itemstacks
[09:20:21] [Client thread/INFO] [FML]: Itemstack injection complete
[09:20:22] [Forge Version Check/INFO] [ForgeVersionCheck]: [Forge] Found status: UP_TO_DATE Target: null
[09:20:23] [Sound Library Loader/INFO]: Starting up SoundSystem...
[09:20:24] [Thread-9/INFO]: Initializing LWJGL OpenAL
[09:20:24] [Thread-9/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[09:20:26] [Client thread/INFO] [FML]: Max texture size: 4096
[09:20:27] [Client thread/INFO]: Created: 16x16 textures-atlas
[09:20:31] [Client thread/INFO] [FML]: Injecting itemstacks
[09:20:31] [Client thread/INFO] [FML]: Itemstack injection complete
[09:20:31] [Client thread/WARN] [FML]: ****************************************
[09:20:31] [Client thread/WARN] [FML]: * Unknown recipe class! de.sanandrew.mods.claysoldiers.crafting.DisruptorRecipe Modders need to register their recipe types with net.minecraftforge.oredict.RecipeSorter
[09:20:31] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.RecipeSorter.getPriority(RecipeSorter.java:237)
[09:20:31] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.RecipeSorter.compare(RecipeSorter.java:172)
[09:20:31] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.RecipeSorter.compare(RecipeSorter.java:52)
[09:20:31] [Client thread/WARN] [FML]: *  at java.util.TimSort.countRunAndMakeAscending(Unknown Source)
[09:20:31] [Client thread/WARN] [FML]: *  at java.util.TimSort.sort(Unknown Source)
[09:20:31] [Client thread/WARN] [FML]: *  at java.util.Arrays.sort(Unknown Source)...
[09:20:31] [Client thread/WARN] [FML]: ****************************************
[09:20:31] [Client thread/WARN] [FML]: ****************************************
[09:20:31] [Client thread/WARN] [FML]: * Unknown recipe class! de.sanandrew.mods.claysoldiers.crafting.DyedSoldierRecipe Modders need to register their recipe types with net.minecraftforge.oredict.RecipeSorter
[09:20:31] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.RecipeSorter.getPriority(RecipeSorter.java:237)
[09:20:31] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.RecipeSorter.compare(RecipeSorter.java:172)
[09:20:31] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.RecipeSorter.compare(RecipeSorter.java:52)
[09:20:31] [Client thread/WARN] [FML]: *  at java.util.TimSort.countRunAndMakeAscending(Unknown Source)
[09:20:31] [Client thread/WARN] [FML]: *  at java.util.TimSort.sort(Unknown Source)
[09:20:31] [Client thread/WARN] [FML]: *  at java.util.Arrays.sort(Unknown Source)...
[09:20:31] [Client thread/WARN] [FML]: ****************************************
[09:20:31] [Client thread/WARN] [FML]: ****************************************
[09:20:31] [Client thread/WARN] [FML]: * Unknown recipe class! de.sanandrew.mods.claysoldiers.crafting.ClearSoldierRecipe Modders need to register their recipe types with net.minecraftforge.oredict.RecipeSorter
[09:20:31] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.RecipeSorter.getPriority(RecipeSorter.java:237)
[09:20:31] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.RecipeSorter.compare(RecipeSorter.java:172)
[09:20:31] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.RecipeSorter.compare(RecipeSorter.java:52)
[09:20:31] [Client thread/WARN] [FML]: *  at java.util.TimSort.countRunAndMakeAscending(Unknown Source)
[09:20:31] [Client thread/WARN] [FML]: *  at java.util.TimSort.sort(Unknown Source)
[09:20:31] [Client thread/WARN] [FML]: *  at java.util.Arrays.sort(Unknown Source)...
[09:20:31] [Client thread/WARN] [FML]: ****************************************
[09:20:31] [Client thread/INFO] [FML]: Forge Mod Loader has successfully loaded 7 mods
[09:20:31] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:mercurius_updater, FMLFileResourcePack:Clay Soldiers Mod, FMLFileResourcePack:SanAndreasPs Mod Library, FMLFileResourcePack:SanAndreasPs Player Model

**Comment by jb043** [comment]
![image](https://cloud.githubusercontent.com/assets/27896388/25306278/bc138944-273e-11e7-9b41-ca6c95e45962.png)

![image](https://cloud.githubusercontent.com/assets/27896388/25306289/e7d73f1c-273e-11e7-9138-7c5e202eca3e.png)

**Comment by SanAndreasP** [comment]
Post your log file (either in /logs/fml-client-latest.log or /logs/latest.log) on https://gist.github.com and provide the link

**Comment by jb043** [comment]
its ok i can still play on 1.5.2 and 1.7.10

**Comment by jb043** [comment]
but im still planning to buy the game

**Comment by jb043** [comment]
![image](https://cloud.githubusercontent.com/assets/27896388/25310513/c12580e8-279a-11e7-8e6d-053e7c98002c.png)
 

![image](https://cloud.githubusercontent.com/assets/27896388/25310532/16a41142-279b-11e7-8ec3-2274b2831491.png)
