### ISSUE TITLE
Can't see soldiers

### ISSUE THREAD

**Issue by chuhanuman** [SanAndreasP/ClaySoldiersMod#211]
Do you use Java 8?
Yes

What version of Minecraft do you use?
1.12.2

What version of MinecraftForge do you use?
14.23.0.2538

What version of SanLib do you use?
1.3

What version of Clay Soldiers do you use?
3.0 alpha 4.1
 
What is the issue / bug you have encountered? Give us a short description.
The clay soldiers do not show up on the screen but I know they are there, because when I use the disruptor they moved. 

How can it be reproduced?
Place soldier in block

Please post your log file (either in /logs/fml-client-latest.log or /logs/latest.log) on https://gist.github.com and provide the link:
https://gist.github.com/chuhanuman/b79a66768550088035c26a62da024099

**Comment by chuhanuman** [comment]
Can you update the mod on twitch?

**Comment by SanAndreasP** [comment]
I see you've joined a server? Or are you hosting a LAN server?

**Comment by chuhanuman** [comment]
I am not on a server

**Comment by SanAndreasP** [comment]
So you're hosting a LAN world then?

**Comment by chuhanuman** [comment]
I am not in multiplayer at all

**Comment by SanAndreasP** [comment]
The log tells me something else:
```
[17:06:37] [Server thread/INFO]: Kihan1234[local:E:d35f4b72] logged in with entity id 1551 at (242.5, 75.0, 248.5)
...
[17:08:27] [Server thread/INFO]: Madduc[/192.168.17.105:61778] logged in with entity id 6915 at (248.5, 67.0, 244.5)
```

Also the log doesn't seem complete. Can you look if you have a fml-client-latest.log file and upload that instead?

**Comment by chuhanuman** [comment]
I changed the world from that lan multiplayer world.  I cannot find fml-client-latest.log in the Minecraft folder. Where should it be?

**Comment by SanAndreasP** [comment]
It should be in the same folder as the latest.log, but not everyone does have it (and it seems like you don't).

The log you gave me is not complete, either. Could you upload the file itself directly somewhere, like https://www.mediafire.com/ ?

**Comment by chuhanuman** [comment]
Are logs for Twitch placed somewhere else? When I looked at my log, it had no mods.

**Comment by chuhanuman** [comment]
I found it! https://www.mediafire.com/file/daz4y52zvscmn6a/latest.log

**Comment by SanAndreasP** [comment]
Okay, I found the error that may cause this, problem is, it's code outside the scope of the mod, as other mods entities seem to have the same problem (like Tinkers' Construct projectiles).

What I suggest you do is update MinecraftForge. Latest is ```14.23.0.2542``` and it does fix some packet issues according to the changelog which also might fix this.
If that does not fix it, then some other mod is messing up the spawn packets for certain entities.
```
java.util.concurrent.ExecutionException: java.lang.RuntimeException: A severe problem occurred during the spawning of an entity at (276.02494696726217, 63.0, 275.0372034198734)
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_25]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1086) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.RuntimeException: A severe problem occurred during the spawning of an entity at (276.02494696726217, 63.0, 275.0372034198734)
	at net.minecraftforge.fml.common.network.internal.EntitySpawnHandler.spawnEntity(EntitySpawnHandler.java:134) ~[EntitySpawnHandler.class:?]
	at net.minecraftforge.fml.common.network.internal.EntitySpawnHandler.process(EntitySpawnHandler.java:63) ~[EntitySpawnHandler.class:?]
	at net.minecraftforge.fml.common.network.internal.EntitySpawnHandler.lambda$channelRead0$0(EntitySpawnHandler.java:55) ~[EntitySpawnHandler.class:?]
	at net.minecraftforge.fml.common.network.internal.EntitySpawnHandler$$Lambda$1959/881516904.run(Unknown Source) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_25]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 9 more
Caused by: io.netty.util.IllegalReferenceCountException: refCnt: 0
	at io.netty.buffer.AbstractByteBuf.ensureAccessible(AbstractByteBuf.java:1408) ~[AbstractByteBuf.class:4.1.9.Final]
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1394) ~[AbstractByteBuf.class:4.1.9.Final]
	at io.netty.buffer.AbstractByteBuf.readInt(AbstractByteBuf.java:766) ~[AbstractByteBuf.class:4.1.9.Final]
	at de.sanandrew.mods.claysoldiers.entity.mount.EntityClayHorse.readSpawnData(EntityClayHorse.java:171) ~[EntityClayHorse.class:?]
	at net.minecraftforge.fml.common.network.internal.EntitySpawnHandler.spawnEntity(EntitySpawnHandler.java:128) ~[EntitySpawnHandler.class:?]
	at net.minecraftforge.fml.common.network.internal.EntitySpawnHandler.process(EntitySpawnHandler.java:63) ~[EntitySpawnHandler.class:?]
	at net.minecraftforge.fml.common.network.internal.EntitySpawnHandler.lambda$channelRead0$0(EntitySpawnHandler.java:55) ~[EntitySpawnHandler.class:?]
	at net.minecraftforge.fml.common.network.internal.EntitySpawnHandler$$Lambda$1959/881516904.run(Unknown Source) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_25]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 9 more
```

**Comment by chuhanuman** [comment]
That didn't work. I think it has to do with graphics. I set the quality on low. In MCA mod, I can't see villagers.

**Comment by SanAndreasP** [comment]
Some mod is messing with the entity client sync, thus some entities don't show up visually.

The only way to find out is to do a binary search:
disable half of your mods and see if it works, if it does, then the mod is in the half taken out. Do the same with that half until you found the mod.

Given that there's no obvious issue on the side of the ClaySoldiers mod, I'm gonna close this for now.

**Comment by Anubis3467** [comment]
I uploaded a video
https://youtu.be/ixWUxWjacBE
http://pasted.co/f6f14198
After I uninstalled half of my mods (actually all except for this) I'm still getting the same error
https://gyazo.com/4758ce0653ee921d6d1aa36137305550

**Comment by SanAndreasP** [comment]
Can you try without DrZharks mods (Custom Spawner and MoCreatures)? I've heard they may cause issues with other mods mob spawning.

**Comment by Anubis3467** [comment]
I did, I uninstalled everything as you can see in the gyazo, I got an other bunch of error lines an hour later and still getting the same error

**Comment by Anubis3467** [comment]
https://gyazo.com/8ea732480c52dbbff66b7d598e0ca872

Look at the 23 and 22 before that one, I know it's a kinda weird way to make you know I uninstalled them, but believe me I did, and did all of that once again right now and the ClaySoldiers aren't beeing rendered

**Comment by SanAndreasP** [comment]
In your video I saw MoCreatures and Spawn Control. Also I don't see that you did as I don't see the whole log there.

I'd appreciate it more if you post the full log via gist.github.com and not just snippets on gyazo.

**Comment by Anubis3467** [comment]
The snippets were just for making you see the highlighted hours xd
Anyways I made a new video about it https://youtu.be/d9mO6A827eY
and here's the gist.github https://gist.github.com/Anubis3467/d3aec9a3d2493de2f4fb36ef09de670d

**Comment by SanAndreasP** [comment]
Okay, so I tested it myself now and it seems to be some sort of issue with the later Forge versions. I recommend for you to stick to the Recommented Forge build (14.23.0.2491).

I'll see if that issue is already known to the Forge team and report it if not.

**Comment by chuhanuman** [comment]
Can you tell me when forge fixes this? My mods don't allow that version.

**Comment by SanAndreasP** [comment]
I have no idea, I hope soon. I'll report it ASAP.
The last version where it still works is 2537, so I dunno if you're able to use that instead.

**Comment by chuhanuman** [comment]
Thank you!

**Comment by SanAndreasP** [comment]
Alright, Forge 2543 is out. I tested it and it works now. :)
