### ISSUE TITLE
Game Output goes blank.

### ISSUE THREAD

**Issue by Giratina720** [SanAndreasP/ClaySoldiersMod#43]
I pressed play and all it says is this.
![screen shot 2015-02-15 at 3 32 42 pm](https://cloud.githubusercontent.com/assets/10970477/6205572/e7af7436-b527-11e4-9029-a5471b7f7cf7.png)

**Comment by SanAndreasP** [comment]
I need the fml-client-latest.log in .minecraft/logs

**Comment by Giratina720** [comment]
Here you go.

[17:02:48] [main/DEBUG] [FML/]: Injecting tracing printstreams for STDOUT/STDERR.
[17:02:48] [main/INFO] [FML/]: Forge Mod Loader version 7.10.85.1240 for Minecraft 1.7.10 loading
[17:02:48] [main/INFO] [FML/]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.6.0_65, running on Mac OS X:x86_64:10.10.1, installed at /System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home
[17:02:48] [main/DEBUG] [FML/]: Java classpath at launch is /Users/kennethng/Library/Application Support/minecraft/libraries/net/minecraftforge/forge/1.7.10-10.13.2.1240/forge-1.7.10-10.13.2.1240.jar:/Users/kennethng/Library/Application Support/minecraft/libraries/net/minecraft/launchwrapper/1.11/launchwrapper-1.11.jar:/Users/kennethng/Library/Application Support/minecraft/libraries/org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.jar:/Users/kennethng/Library/Application Support/minecraft/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar:/Users/kennethng/Library/Application Support/minecraft/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar:/Users/kennethng/Library/Application Support/minecraft/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar:/Users/kennethng/Library/Application Support/minecraft/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar:/Users/kennethng/Library/Application Support/minecraft/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar:/Users/kennethng/Library/Application Support/minecraft/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar:/Users/kennethng/Library/Application Support/minecraft/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar:/Users/kennethng/Library/Application Support/minecraft/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar:/Users/kennethng/Library/Application Support/minecraft/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar:/Users/kennethng/Library/Application Support/minecraft/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar:/Users/kennethng/Library/Application Support/minecraft/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar:/Users/kennethng/Library/Application Support/minecraft/libraries/net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar:/Users/kennethng/Library/Application Support/minecraft/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar:/Users/kennethng/Library/Application Support/minecraft/libraries/com/mojang/realms/1.3.5/realms-1.3.5.jar:/Users/kennethng/Library/Application Support/minecraft/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar:/Users/kennethng/Library/Application Support/minecraft/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar:/Users/kennethng/Library/Application Support/minecraft/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar:/Users/kennethng/Library/Application Support/minecraft/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar:/Users/kennethng/Library/Application Support/minecraft/libraries/java3d/vecmath/1.3.1/vecmath-1.3.1.jar:/Users/kennethng/Library/Application Support/minecraft/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar:/Users/kennethng/Library/Application Support/minecraft/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar:/Users/kennethng/Library/Application Support/minecraft/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar:/Users/kennethng/Library/Application Support/minecraft/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar:/Users/kennethng/Library/Application Support/minecraft/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar:/Users/kennethng/Library/Application Support/minecraft/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar:/Users/kennethng/Library/Application Support/minecraft/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar:/Users/kennethng/Library/Application Support/minecraft/libraries/io/netty/netty-all/4.0.10.Final/netty-all-4.0.10.Final.jar:/Users/kennethng/Library/Application Support/minecraft/libraries/com/google/guava/guava/16.0/guava-16.0.jar:/Users/kennethng/Library/Application Support/minecraft/libraries/org/apache/commons/commons-lang3/3.2.1/commons-lang3-3.2.1.jar:/Users/kennethng/Library/Application Support/minecraft/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar:/Users/kennethng/Library/Application Support/minecraft/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar:/Users/kennethng/Library/Application Support/minecraft/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar:/Users/kennethng/Library/Application Support/minecraft/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar:/Users/kennethng/Library/Application Support/minecraft/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar:/Users/kennethng/Library/Application Support/minecraft/libraries/com/mojang/authlib/1.5.16/authlib-1.5.16.jar:/Users/kennethng/Library/Application Support/minecraft/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.jar:/Users/kennethng/Library/Application Support/minecraft/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar:/Users/kennethng/Library/Application Support/minecraft/libraries/org/lwjgl/lwjgl/lwjgl/2.9.1/lwjgl-2.9.1.jar:/Users/kennethng/Library/Application Support/minecraft/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.1/lwjgl_util-2.9.1.jar:/Users/kennethng/Library/Application Support/minecraft/libraries/tv/twitch/twitch/5.16/twitch-5.16.jar:/Users/kennethng/Library/Application Support/minecraft/versions/1.7.10-Forge10.13.2.1240/1.7.10-Forge10.13.2.1240.jar
[17:02:48] [main/DEBUG] [FML/]: Java library path at launch is /Users/kennethng/Library/Application Support/minecraft/versions/1.7.10-Forge10.13.2.1240/1.7.10-Forge10.13.2.1240-natives-1423789365522852000
[17:02:48] [main/DEBUG] [FML/]: Enabling runtime deobfuscation
[17:02:48] [main/DEBUG] [FML/]: Instantiating coremod class FMLCorePlugin
[17:02:48] [main/DEBUG] [FML/]: Added access transformer class cpw.mods.fml.common.asm.transformers.AccessTransformer to enqueued access transformers
[17:02:48] [main/DEBUG] [FML/]: Enqueued coremod FMLCorePlugin
[17:02:48] [main/DEBUG] [FML/]: Instantiating coremod class FMLForgePlugin
[17:02:48] [main/DEBUG] [FML/]: Added access transformer class net.minecraftforge.transformers.ForgeAccessTransformer to enqueued access transformers
[17:02:48] [main/DEBUG] [FML/]: Enqueued coremod FMLForgePlugin
[17:02:48] [main/DEBUG] [FML/]: All fundamental core mods are successfully located
[17:02:48] [main/DEBUG] [FML/]: Attempting to load commandline specified mods, relative to /Users/kennethng/Library/Application Support/minecraft
[17:02:48] [main/DEBUG] [FML/]: Discovering coremods
[17:02:48] [main/DEBUG] [FML/]: Examining for coremod candidacy ClaySoldiersMod-1.7.10-2.0.0-beta.2.jar
[17:02:49] [main/DEBUG] [FML/]: Not found coremod data in ClaySoldiersMod-1.7.10-2.0.0-beta.2.jar
[17:02:49] [main/DEBUG] [FML/]: Examining for coremod candidacy SAPManPack-1.7.10-2.4.0.jar
[17:02:49] [main/TRACE] [FML/]: Found FMLCorePluginContainsFMLMod marker in SAPManPack-1.7.10-2.4.0.jar, it will be examined later for regular @Mod instances
[17:02:49] [main/DEBUG] [FML/]: Instantiating coremod class ManPackLoadingPlugin
[17:02:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:461]: java.lang.UnsupportedClassVersionError: de/sanandrew/core/manpack/init/ManPackLoadingPlugin : Unsupported major.minor version 51.0
[17:02:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:464]: 	at java.lang.ClassLoader.defineClass1(Native Method)
[17:02:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:464]: 	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
[17:02:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:464]: 	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
[17:02:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:464]: 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
[17:02:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:464]: 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
[17:02:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:464]: 	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
[17:02:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:464]: 	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
[17:02:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:464]: 	at java.security.AccessController.doPrivileged(Native Method)
[17:02:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:464]: 	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
[17:02:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:464]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117)
[17:02:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:464]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
[17:02:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:464]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
[17:02:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:464]: 	at java.lang.Class.forName0(Native Method)
[17:02:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:464]: 	at java.lang.Class.forName(Class.java:249)
[17:02:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:417)
[17:02:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:346)
[17:02:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:214)
[17:02:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90)
[17:02:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67)
[17:02:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34)
[17:02:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126)
[17:02:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:464]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[17:02:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:464]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[17:02:49] [main/ERROR] [FML/]: An error occurred trying to configure the minecraft home at /Users/kennethng/Library/Application Support/minecraft for Forge Mod Loader
java.lang.UnsupportedClassVersionError: de/sanandrew/core/manpack/init/ManPackLoadingPlugin : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.6.0_65]
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637) ~[?:1.6.0_65]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621) ~[?:1.6.0_65]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141) ~[?:1.6.0_65]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283) ~[?:1.6.0_65]
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58) ~[?:1.6.0_65]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197) ~[?:1.6.0_65]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.6.0_65]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190) ~[?:1.6.0_65]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306) ~[?:1.6.0_65]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247) ~[?:1.6.0_65]
	at java.lang.Class.forName0(Native Method) ~[?:1.6.0_65]
	at java.lang.Class.forName(Class.java:249) ~[?:1.6.0_65]
	at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:417) ~[forge-1.7.10-10.13.2.1240.jar:?]
	at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:346) ~[forge-1.7.10-10.13.2.1240.jar:?]
	at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:214) ~[forge-1.7.10-10.13.2.1240.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90) [forge-1.7.10-10.13.2.1240.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67) [forge-1.7.10-10.13.2.1240.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34) [forge-1.7.10-10.13.2.1240.jar:?]
	at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126) [forge-1.7.10-10.13.2.1240.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
[17:02:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:461]: java.lang.UnsupportedClassVersionError: de/sanandrew/core/manpack/init/ManPackLoadingPlugin : Unsupported major.minor version 51.0
[17:02:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:464]: 	at java.lang.ClassLoader.defineClass1(Native Method)
[17:02:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:464]: 	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
[17:02:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:464]: 	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
[17:02:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:464]: 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
[17:02:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:464]: 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
[17:02:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:464]: 	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
[17:02:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:464]: 	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
[17:02:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:464]: 	at java.security.AccessController.doPrivileged(Native Method)
[17:02:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:464]: 	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
[17:02:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:464]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117)
[17:02:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:464]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
[17:02:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:464]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
[17:02:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:464]: 	at java.lang.Class.forName0(Native Method)
[17:02:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:464]: 	at java.lang.Class.forName(Class.java:249)
[17:02:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:417)
[17:02:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:346)
[17:02:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:214)
[17:02:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90)
[17:02:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67)
[17:02:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34)
[17:02:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126)
[17:02:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:464]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[17:02:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:464]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by SanAndreasP** [comment]
See #23
