### ISSUE TITLE
Server not working? tested using cauldron and regular forge.

### ISSUE THREAD

**Issue by Froosty11** [SanAndreasP/ClaySoldiersMod#45]
So when i try to start my server, no log appears in the server-box-thingy, i have tested forge and cauldron...? what am i supposed to do (on forge i cant log in and the server is like [LAG!!!] and i cant seem to find a log)

Logs:
Cauldron:
[13:27:00] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLServerTweaker
[13:27:00] [main/INFO]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLServerTweaker
[13:27:00] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLServerTweaker
[13:27:00] [main/INFO]: Forge Mod Loader version 7.10.85.1272 for Minecraft 1.7.10 loading
[13:27:01] [main/INFO]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.7.0_60, running on Windows 7:amd64:6.1, installed at C:\Program Files\Java\jre7
[13:27:05] [main/WARN]: The following coremods do not have a @MCVersion annotation. They may cause problems if this is not the correct version of Minecraft for them.
[13:27:05] [main/WARN]: Missing @MCVersion: mods.battlegear2.coremod.BattlegearLoadingPlugin  codechicken.core.launch.CodeChickenCorePlugin  mods.immibis.microblocks.coremod.MicroblocksCoreMod  mmmlibx.lib.multiModel.MMMLoader.MMMCoremod  codechicken.nei.asm.NEICorePlugin  openblocks.OpenBlocksCorePlugin  openmods.OpenModsCorePlugin  thaumcraft.codechicken.core.launch.DepLoader  
[13:27:05] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[13:27:05] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
[13:27:05] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[13:27:05] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[13:27:05] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[13:27:07] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[13:27:07] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[13:27:07] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[13:27:07] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[13:27:07] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[13:27:07] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[13:27:07] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[13:27:07] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[13:27:07] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[13:27:07] [main/INFO]: openmods.config.simple.ConfigProcessor.process(ConfigProcessor.java:73): Parsing config file '.\config\OpenModsLibCore.json'
[13:27:07] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[13:27:07] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLDeobfTweaker
[13:27:08] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[13:27:08] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.TerminalTweaker
[13:27:08] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.TerminalTweaker
[13:27:08] [main/INFO]: M&B - Patching Class EntityPlayer (yz)
[13:27:08] [main/INFO]: 	Adding new fields to EntityPlayer
[13:27:08] [main/INFO]: 	Patching constructor in EntityPlayer
[13:27:08] [main/INFO]: 	Patching method onUpdate in EntityPlayer
[13:27:08] [main/INFO]: 	Patching method onItemUseFinish in EntityPlayer
[13:27:08] [main/INFO]: 	Patching method setCurrentItemOrArmor in EntityPlayer
[13:27:08] [main/INFO]: 	Creating new methods in EntityPlayer
[13:27:08] [main/INFO]: M&B - Patching Class EntityPlayer done
[13:27:08] [main/INFO]: [OpenBlocks] Trying to patch EntityPlayer.isInBed (class: yz)
[13:27:08] [main/INFO]: [OpenBlocks] isInBed patch applied. Enabling sleeping bags
[13:27:08] [main/INFO]: Class net/minecraft/entity/player/EntityPlayer successfully transformed!
[13:27:09] [main/INFO]: Class net/minecraft/entity/EntityLivingBase successfully transformed!
[13:27:09] [main/INFO]: Class net/minecraft/entity/Entity successfully transformed!
[13:27:09] [main/INFO]: Launching wrapped minecraft {net.minecraft.server.MinecraftServer}
[13:27:10] [main/INFO]: Class net/minecraft/entity/projectile/EntityThrowable successfully transformed!
[13:27:10] [main/INFO]: Class net/minecraft/potion/Potion successfully transformed!
[13:27:10] [main/INFO]: M&B - Patching Class ItemStack (add)
[13:27:10] [main/INFO]: M&B - Patching Class ItemStack done
[13:27:10] [main/ERROR]: Unable to launch
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_60]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_60]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_60]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_60]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_60]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_60]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_60]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_60]
	at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43) [modpack.jar:git-Cauldron-MCPC-Plus-1.7.10-1.1272.06.215]
	at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12) [modpack.jar:git-Cauldron-MCPC-Plus-1.7.10-1.1272.06.215]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/entity/monster/EntityEnderman
	at net.minecraft.entity.EntityList.<clinit>(EntityList.java:282) ~[sg.class:?]
	at net.minecraft.item.ItemMonsterPlacer.func_77653_i(ItemMonsterPlacer.java:39) ~[aee.class:?]
	at net.minecraft.item.ItemStack.func_82833_r(ItemStack.java:487) ~[add.class:?]
	at net.minecraft.item.ItemStack.func_151000_E(ItemStack.java:819) ~[add.class:?]
	at net.minecraft.stats.StatList.func_75925_c(StatList.java:139) ~[pp.class:?]
	at net.minecraft.stats.StatList.func_151178_a(StatList.java:59) ~[pp.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:717) ~[kl.class:?]
	at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1579) ~[MinecraftServer.class:?]
	... 12 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.entity.monster.EntityEnderman
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_60]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_60]
	at net.minecraft.entity.EntityList.<clinit>(EntityList.java:282) ~[sg.class:?]
	at net.minecraft.item.ItemMonsterPlacer.func_77653_i(ItemMonsterPlacer.java:39) ~[aee.class:?]
	at net.minecraft.item.ItemStack.func_82833_r(ItemStack.java:487) ~[add.class:?]
	at net.minecraft.item.ItemStack.func_151000_E(ItemStack.java:819) ~[add.class:?]
	at net.minecraft.stats.StatList.func_75925_c(StatList.java:139) ~[pp.class:?]
	at net.minecraft.stats.StatList.func_151178_a(StatList.java:59) ~[pp.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:717) ~[kl.class:?]
	at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1579) ~[MinecraftServer.class:?]
	... 12 more
Caused by: de.sanandrew.core.manpack.transformer.ASMHelper$InvalidNeedleException: Needle not found in Haystack!
	at de.sanandrew.core.manpack.transformer.ASMHelper.findFirstNodeFromNeedle(ASMHelper.java:58) ~[SAPManPack-1.7.10-2.4.0.jar:?]
	at de.sanandrew.core.manpack.transformer.TransformEnderman.transformTeleportTo(TransformEnderman.java:91) ~[SAPManPack-1.7.10-2.4.0.jar:?]
	at de.sanandrew.core.manpack.transformer.TransformEnderman.transform(TransformEnderman.java:39) ~[SAPManPack-1.7.10-2.4.0.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_60]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_60]
	at net.minecraft.entity.EntityList.<clinit>(EntityList.java:282) ~[sg.class:?]
	at net.minecraft.item.ItemMonsterPlacer.func_77653_i(ItemMonsterPlacer.java:39) ~[aee.class:?]
	at net.minecraft.item.ItemStack.func_82833_r(ItemStack.java:487) ~[add.class:?]
	at net.minecraft.item.ItemStack.func_151000_E(ItemStack.java:819) ~[add.class:?]
	at net.minecraft.stats.StatList.func_75925_c(StatList.java:139) ~[pp.class:?]
	at net.minecraft.stats.StatList.func_151178_a(StatList.java:59) ~[pp.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:717) ~[kl.class:?]
	at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1579) ~[MinecraftServer.class:?]
	... 12 more

**Comment by SanAndreasP** [comment]
Cauldron is not supported, since it's discontinued. Try a vanilla server with Forge installed.
I've also heard M&B Battlegear 2 seems to have a problem with my coremod. Try w/o it and see if that works, and if it does, I'll look into it.

**Comment by Froosty11** [comment]
ok thanks ill test that.

**Comment by SanAndreasP** [comment]
If M&B Battlegear 2 is a cause of the crash, I have to see what I can do.

There's an API in development called Sponge. Cauldron devs work on it as well, but dunno if it's out yet nor if not, when it will

**Comment by Froosty11** [comment]
ok thx for help and for answering so fast!

//Froosty11

**Comment by SanAndreasP** [comment]
I'll close this now, since the Manager Pack v2.5(.1) removes the transformer causing this crash, and also possibly fixes the most common cauldron crash.
