### ISSUE TITLE
Soldiers Shild wont load

### ISSUE THREAD

**Issue by jake0407** [SanAndreasP/ClaySoldiersMod#51]
I try giving a soldier a shield and the game crashes, says it wont render the shield. error log:
---- Minecraft Crash Report ----
// Why is it breaking :(

Time: 2/23/15 12:13 PM
Description: Rendering entity in world

java.lang.NoClassDefFoundError: de/sanandrew/core/manpack/util/client/ItemRenderHelper
	at de.sanandrew.mods.claysoldiers.client.event.SoldierLeftHandRenderHandler.renderShield(SoldierLeftHandRenderHandler.java:83)
	at de.sanandrew.mods.claysoldiers.client.event.SoldierLeftHandRenderHandler.onSoldierRender(SoldierLeftHandRenderHandler.java:47)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_18_SoldierLeftHandRenderHandler_onSoldierRender_SoldierRenderEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at de.sanandrew.mods.claysoldiers.client.render.entity.RenderClayMan.func_77029_c(RenderClayMan.java:55)
	at net.minecraft.client.renderer.entity.RendererLivingEntity.func_76986_a(RendererLivingEntity.java:213)
	at net.minecraft.client.renderer.entity.RenderLiving.func_76986_a(SourceFile:23)
	at net.minecraft.client.renderer.entity.RenderBiped.func_76986_a(RenderBiped.java:164)
	at de.sanandrew.mods.claysoldiers.client.render.entity.RenderClayMan.doRenderClayMan(RenderClayMan.java:84)
	at de.sanandrew.mods.claysoldiers.client.render.entity.RenderClayMan.func_76986_a(RenderClayMan.java:44)
	at net.minecraft.client.renderer.entity.RenderBiped.func_76986_a(RenderBiped.java:361)
	at net.minecraft.client.renderer.entity.RenderManager.func_147939_a(RenderManager.java:293)
	at net.minecraft.client.renderer.entity.RenderManager.func_147936_a(RenderManager.java:271)
	at net.minecraft.client.renderer.entity.RenderManager.func_147937_a(RenderManager.java:244)
	at net.minecraft.client.renderer.RenderGlobal.func_147589_a(RenderGlobal.java:471)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1224)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1011)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:989)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: de.sanandrew.core.manpack.util.client.ItemRenderHelper
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 27 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 29 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at de.sanandrew.mods.claysoldiers.client.event.SoldierLeftHandRenderHandler.renderShield(SoldierLeftHandRenderHandler.java:83)
	at de.sanandrew.mods.claysoldiers.client.event.SoldierLeftHandRenderHandler.onSoldierRender(SoldierLeftHandRenderHandler.java:47)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_18_SoldierLeftHandRenderHandler_onSoldierRender_SoldierRenderEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at de.sanandrew.mods.claysoldiers.client.render.entity.RenderClayMan.func_77029_c(RenderClayMan.java:55)
	at net.minecraft.client.renderer.entity.RendererLivingEntity.func_76986_a(RendererLivingEntity.java:213)
	at net.minecraft.client.renderer.entity.RenderLiving.func_76986_a(SourceFile:23)
	at net.minecraft.client.renderer.entity.RenderBiped.func_76986_a(RenderBiped.java:164)
	at de.sanandrew.mods.claysoldiers.client.render.entity.RenderClayMan.doRenderClayMan(RenderClayMan.java:84)
	at de.sanandrew.mods.claysoldiers.client.render.entity.RenderClayMan.func_76986_a(RenderClayMan.java:44)
	at net.minecraft.client.renderer.entity.RenderBiped.func_76986_a(RenderBiped.java:361)

-- Entity being rendered --
Details:
	Entity Type: claysoldiers.clayman (de.sanandrew.mods.claysoldiers.entity.EntityClayMan)
	Entity ID: 1024015
	Entity Name: entity.claysoldiers.clayman.name
	Entity's Exact location: -305.57, 5.00, -321.30
	Entity's Block location: World: (-306,5,-322), Chunk: (at 14,0,14 in -20,-21; contains blocks -320,0,-336 to -305,255,-321), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Entity's Momentum: 0.00, -0.08, -0.02

-- Renderer details --
Details:
	Assigned renderer: de.sanandrew.mods.claysoldiers.client.render.entity.RenderClayMan@11acb3a
	Location: 0.52,-1.62,-1.44 - World: (0,-2,-2), Chunk: (at 0,-1,14 in 0,-1; contains blocks 0,0,-16 to 15,255,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Rotation: 183.25055
	Delta: 0.084530234
Stacktrace:
	at net.minecraft.client.renderer.entity.RenderManager.func_147939_a(RenderManager.java:293)
	at net.minecraft.client.renderer.entity.RenderManager.func_147936_a(RenderManager.java:271)
	at net.minecraft.client.renderer.entity.RenderManager.func_147937_a(RenderManager.java:244)
	at net.minecraft.client.renderer.RenderGlobal.func_147589_a(RenderGlobal.java:471)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1224)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['dvr996'/499538, l='MpServer', x=-306.10, y=6.62, z=-319.76]]
	Chunk stats: MultiplayerChunkCache: 289, 289
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-158,4,229), Chunk: (at 2,0,5 in -10,14; contains blocks -160,0,224 to -145,255,239), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 6174 game time, 6174 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 33 total; [EntityClayMan['entity.claysoldiers.clayman.name'/1024015, l='MpServer', x=-305.57, y=5.00, z=-321.30], EntityVillager['Villager'/525955, l='MpServer', x=-336.78, y=6.00, z=-337.34], EntityBat['Bat'/1019330, l='MpServer', x=-303.81, y=10.41, z=-332.73], EntityVillager['Villager'/552154, l='MpServer', x=-318.50, y=5.00, z=-337.88], EntityBat['Bat'/652506, l='MpServer', x=-254.25, y=13.68, z=-335.89], EntityClientPlayerMP['dvr996'/499538, l='MpServer', x=-306.10, y=6.62, z=-319.76], EntityBat['Bat'/611793, l='MpServer', x=-317.81, y=6.10, z=-339.25], EntityBat['Bat'/616535, l='MpServer', x=-265.34, y=6.70, z=-248.44], EntityVillager['Villager'/542248, l='MpServer', x=-315.03, y=4.50, z=-348.84], EntityVillager['Villager'/542250, l='MpServer', x=-306.34, y=5.00, z=-338.66], EntityVillager['Villager'/542251, l='MpServer', x=-314.31, y=4.00, z=-349.63], EntityVillager['Villager'/527788, l='MpServer', x=-318.50, y=5.00, z=-322.78], EntityVillager['Villager'/527853, l='MpServer', x=-317.91, y=4.00, z=-351.94], EntityVillager['Villager'/527854, l='MpServer', x=-347.25, y=5.00, z=-340.69], EntityVillager['Villager'/542241, l='MpServer', x=-317.25, y=4.00, z=-351.00], EntityVillager['Villager'/542242, l='MpServer', x=-302.94, y=5.00, z=-329.44], EntityVillager['Villager'/542243, l='MpServer', x=-306.78, y=7.00, z=-347.50], EntityVillager['Villager'/542244, l='MpServer', x=-325.31, y=4.00, z=-344.59], EntityBat['Bat'/542245, l='MpServer', x=-305.81, y=7.10, z=-348.75], EntityVillager['Villager'/542247, l='MpServer', x=-305.63, y=5.00, z=-336.16], EntityBat['Bat'/574393, l='MpServer', x=-328.00, y=7.10, z=-363.25], EntityBat['Bat'/574394, l='MpServer', x=-323.25, y=8.10, z=-369.94], EntityVillager['Villager'/575227, l='MpServer', x=-335.09, y=5.00, z=-341.38], EntityVillager['Villager'/575228, l='MpServer', x=-340.34, y=4.00, z=-334.22], EntityVillager['Villager'/575229, l='MpServer', x=-336.06, y=5.00, z=-342.50], EntityVillager['Villager'/580402, l='MpServer', x=-344.28, y=4.00, z=-335.28], EntityVillager['Villager'/580403, l='MpServer', x=-341.31, y=5.00, z=-319.69], EntityVillager['Villager'/580404, l='MpServer', x=-341.59, y=5.00, z=-318.78], EntityVillager['Villager'/580405, l='MpServer', x=-330.31, y=4.00, z=-330.31], EntityVillager['Villager'/580406, l='MpServer', x=-316.31, y=4.00, z=-353.69], EntityBat['Bat'/574391, l='MpServer', x=-322.25, y=7.10, z=-363.25], EntityVillager['Villager'/580407, l='MpServer', x=-321.75, y=4.00, z=-353.38], EntityBat['Bat'/623734, l='MpServer', x=-318.25, y=7.10, z=-341.44]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2432)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:909)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (x86) version 6.1
	Java Version: 1.8.0_31, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 167962072 bytes (160 MB) / 297885696 bytes (284 MB) up to 523501568 bytes (499 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 5 mods loaded, 5 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	FML{7.10.85.1291} [Forge Mod Loader] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	Forge{10.13.2.1291} [Minecraft Forge] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	sapmanpack{2.3.0} [SanAndreasPs Manager Pack CORE edition] (SAPManPack-1.7.10-2.3.0 (1).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	claysoldiers{2.0.0b} [Clay Soldiers Mod] (ClaySoldiersMod-1.7.10-2.0.0b (1).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	Launched Version: 1.7.10-Forge10.13.2.1291
	LWJGL: 2.9.1
	OpenGL: GeForce GTX 745/PCIe/SSE2 GL version 4.4.0, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

pretty much all other items work, just the shield wont render

**Comment by SanAndreasP** [comment]
Update the Manager Pack and Clay Soldiers
