### ISSUE TITLE
Sapmanpack crashes me

### ISSUE THREAD

**Issue by tmf5055** [SanAndreasP/ClaySoldiersMod#56]
[21:40:50] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[21:40:50] [main/INFO] [LaunchWrapper]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[21:40:50] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
[21:40:50] [main/INFO] [FML]: Forge Mod Loader version 7.2.217.1147 for Minecraft 1.7.2 loading
[21:40:50] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.6.0_65, running on Mac OS X:x86_64:10.9.5, installed at /System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home
java.lang.UnsupportedClassVersionError: de/sanandrew/core/manpack/init/ManPackLoadingPlugin : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:115)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:249)
	at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:383)
	at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:312)
	at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:214)
	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90)
	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67)
	at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34)
	at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:124)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:114)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[21:40:50] [main/ERROR] [FML]: An error occurred trying to configure the minecraft home at /Users/Sam/Library/Application Support/minecraft for Forge Mod Loader
java.lang.UnsupportedClassVersionError: de/sanandrew/core/manpack/init/ManPackLoadingPlugin : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.6.0_65]
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637) ~[?:1.6.0_65]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621) ~[?:1.6.0_65]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141) ~[?:1.6.0_65]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283) ~[?:1.6.0_65]
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58) ~[?:1.6.0_65]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197) ~[?:1.6.0_65]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.6.0_65]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190) ~[?:1.6.0_65]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:115) ~[launchwrapper-1.9.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306) ~[?:1.6.0_65]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247) ~[?:1.6.0_65]
	at java.lang.Class.forName0(Native Method) ~[?:1.6.0_65]
	at java.lang.Class.forName(Class.java:249) ~[?:1.6.0_65]
	at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:383) ~[forge-1.7.2-10.12.2.1147.jar:?]
	at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:312) ~[forge-1.7.2-10.12.2.1147.jar:?]
	at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:214) ~[forge-1.7.2-10.12.2.1147.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90) [forge-1.7.2-10.12.2.1147.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67) [forge-1.7.2-10.12.2.1147.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34) [forge-1.7.2-10.12.2.1147.jar:?]
	at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:124) [forge-1.7.2-10.12.2.1147.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:114) [launchwrapper-1.9.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.9.jar:?]
Exception in thread "main" java.lang.UnsupportedClassVersionError: de/sanandrew/core/manpack/init/ManPackLoadingPlugin : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:115)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:249)
	at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:383)
	at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:312)
	at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:214)
	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90)
	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67)
	at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34)
	at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:124)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:114)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
This is the screen i get when it crashes

i have the most recent version of everything (forge is the most recent 1.7.10)

 i am on OSX

I AM ON JAVA 8

Please answer it soon this is the first mod i ever had and i want to see how far it has progressed.

**Comment by Spartan322** [comment]
are you sure all mods you are using with the core are at the current version and that the core is at the current version.

**Comment by SanAndreasP** [comment]
21:40:50] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.6.0_65, running on Mac OS X:x86_64:10.9.5, installed at /System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home
java.lang.UnsupportedClassVersionError: de/sanandrew/core/manpack/init/ManPackLoadingPlugin : Unsupported major.minor version 51.0


Use Java 7
See SanAndreasP/ClaySoldiersMod#23
