### ISSUE TITLE
BUG!!!!!

### ISSUE THREAD

**Issue by TheOcelot4000** [SanAndreasP/ClaySoldiersMod#71]
This is my Bug that i have with the 1.6.2 version of the clay soldiers mod for minecraft.
Have fun with it =P

-- Head --
Stacktrace:
at java.util.HashMap$HashIterator.nextEntry(HashMap.java:793)
at java.util.HashMap$KeyIterator.next(HashMap.java:828)
at sanandreasp.mods.ClaySoldiersMod.entity.EntityClayMan.func_70097_a(EntityClayMan.java:130)
at sanandreasp.mods.ClaySoldiersMod.entity.EntityClayMan.func_70626_be(EntityClayMan.java:242)
at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:1999)
at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:441)
at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1826)
at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:257)
at sanandreasp.mods.ClaySoldiersMod.entity.EntityClayMan.func_70071_h_(EntityClayMan.java:120)
at net.minecraft.world.World.func_72866_a(World.java:2350)
at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:721)
at net.minecraft.world.World.func_72870_g(World.java:2311)

**Comment by SanAndreasP** [comment]
The 1.6.2 version is no longer supported. There's an 1.7.10 beta out, use that.
