### ISSUE TITLE
mine doesn't load :/ 

### ISSUE THREAD

**Issue by 1231chorosso** [SanAndreasP/ClaySoldiersMod#75]
for some reason when i load my game with the mod and sapmanpack it doesn't load all it does is half load the game output screen and then do nothing know crash no anything. I'm also using a macbook pro so i think that might have something to do with it.

**Comment by SanAndreasP** [comment]
Can't help you without logs.
You can find them in .minecraft/logs as fml-client-latest.log
Post the content of it on http://gist.github.com and provide the link.

**Comment by 1231chorosso** [comment]
2015-02-15 13:58:51 [INFO] [ForgeModLoader] Forge Mod Loader version 6.4.49.965 for Minecraft 1.6.4 loading
2015-02-15 13:58:51 [INFO] [ForgeModLoader] Java is Java HotSpot(TM) 64-Bit Server VM, version 1.6.0_65, running on Mac OS X:x86_64:10.9.5, installed at /System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home
2015-02-15 13:58:51 [FINE] [ForgeModLoader] Java classpath at launch is /Users/helenclark/Library/Application Support/minecraft/libraries/net/minecraftforge/minecraftforge/9.11.1.965/minecraftforge-9.11.1.965.jar:/Users/helenclark/Library/Application Support/minecraft/libraries/net/minecraft/launchwrapper/1.8/launchwrapper-1.8.jar:/Users/helenclark/Library/Application Support/minecraft/libraries/org/ow2/asm/asm-all/4.1/asm-all-4.1.jar:/Users/helenclark/Library/Application Support/minecraft/libraries/org/scala-lang/scala-library/2.10.2/scala-library-2.10.2.jar:/Users/helenclark/Library/Application Support/minecraft/libraries/org/scala-lang/scala-compiler/2.10.2/scala-compiler-2.10.2.jar:/Users/helenclark/Library/Application Support/minecraft/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar:/Users/helenclark/Library/Application Support/minecraft/libraries/net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar:/Users/helenclark/Library/Application Support/minecraft/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar:/Users/helenclark/Library/Application Support/minecraft/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar:/Users/helenclark/Library/Application Support/minecraft/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar:/Users/helenclark/Library/Application Support/minecraft/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar:/Users/helenclark/Library/Application Support/minecraft/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar:/Users/helenclark/Library/Application Support/minecraft/libraries/argo/argo/2.25_fixed/argo-2.25_fixed.jar:/Users/helenclark/Library/Application Support/minecraft/libraries/org/bouncycastle/bcprov-jdk15on/1.47/bcprov-jdk15on-1.47.jar:/Users/helenclark/Library/Application Support/minecraft/libraries/com/google/guava/guava/14.0/guava-14.0.jar:/Users/helenclark/Library/Application Support/minecraft/libraries/org/apache/commons/commons-lang3/3.1/commons-lang3-3.1.jar:/Users/helenclark/Library/Application Support/minecraft/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar:/Users/helenclark/Library/Application Support/minecraft/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar:/Users/helenclark/Library/Application Support/minecraft/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar:/Users/helenclark/Library/Application Support/minecraft/libraries/com/google/code/gson/gson/2.2.2/gson-2.2.2.jar:/Users/helenclark/Library/Application Support/minecraft/libraries/org/lwjgl/lwjgl/lwjgl/2.9.0/lwjgl-2.9.0.jar:/Users/helenclark/Library/Application Support/minecraft/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.0/lwjgl_util-2.9.0.jar:/Users/helenclark/Library/Application Support/minecraft/versions/1.6.4-Forge9.11.1.965/1.6.4-Forge9.11.1.965.jar
2015-02-15 13:58:51 [FINE] [ForgeModLoader] Java library path at launch is /Users/helenclark/Library/Application Support/minecraft/versions/1.6.4-Forge9.11.1.965/1.6.4-Forge9.11.1.965-natives-1424008730179280000
2015-02-15 13:58:51 [FINE] [ForgeModLoader] Enabling runtime deobfuscation
2015-02-15 13:58:51 [FINE] [ForgeModLoader] Instantiating coremod class FMLCorePlugin
2015-02-15 13:58:51 [FINE] [ForgeModLoader] Enqueued coremod FMLCorePlugin
2015-02-15 13:58:51 [FINE] [ForgeModLoader] Instantiating coremod class FMLForgePlugin
2015-02-15 13:58:51 [FINE] [ForgeModLoader] Enqueued coremod FMLForgePlugin
2015-02-15 13:58:51 [FINE] [ForgeModLoader] All fundamental core mods are successfully located
2015-02-15 13:58:51 [FINE] [ForgeModLoader] Discovering coremods
2015-02-15 13:58:51 [FINE] [ForgeModLoader] Examining for coremod candidacy Farseek-1.0.1.jar
2015-02-15 13:58:51 [FINEST] [ForgeModLoader] Found FMLCorePluginContainsFMLMod marker in Farseek-1.0.1.jar, it will be examined later for regular @Mod instances
2015-02-15 13:58:51 [FINE] [ForgeModLoader] Instantiating coremod class FarseekCoreMod
2015-02-15 13:58:51 [WARNING] [ForgeModLoader] The coremod farseek.core.FarseekCoreMod does not have a MCVersion annotation, it may cause issues with this version of Minecraft
2015-02-15 13:58:51 [FINE] [ForgeModLoader] Enqueued coremod FarseekCoreMod
2015-02-15 13:58:51 [FINE] [ForgeModLoader] Examining for coremod candidacy HookShotMOD_1710_2.jar
2015-02-15 13:58:51 [FINE] [ForgeModLoader] Not found coremod data in HookShotMOD_1710_2.jar
2015-02-15 13:58:51 [FINE] [ForgeModLoader] Examining for coremod candidacy Numina-0.4.0.87.jar
2015-02-15 13:58:51 [FINE] [ForgeModLoader] Not found coremod data in Numina-0.4.0.87.jar
2015-02-15 13:58:51 [FINE] [ForgeModLoader] Examining for coremod candidacy Starminer1710-0.9.8.jar
2015-02-15 13:58:51 [FINEST] [ForgeModLoader] Found FMLCorePluginContainsFMLMod marker in Starminer1710-0.9.8.jar, it will be examined later for regular @Mod instances
2015-02-15 13:58:51 [FINE] [ForgeModLoader] Instantiating coremod class SMPlugin
2015-02-15 13:58:51 [SEVERE] [ForgeModLoader] The coremod jp.mc.ancientred.starminer.core.SMPlugin is requesting minecraft version 1.7.10 and minecraft is 1.6.4. It will be ignored.
2015-02-15 13:58:51 [FINE] [ForgeModLoader] Examining for coremod candidacy Streams-0.1.2.jar
2015-02-15 13:58:51 [FINEST] [ForgeModLoader] Found FMLCorePluginContainsFMLMod marker in Streams-0.1.2.jar, it will be examined later for regular @Mod instances
2015-02-15 13:58:51 [FINE] [ForgeModLoader] Instantiating coremod class StreamsCoreMod
2015-02-15 13:58:51 [WARNING] [ForgeModLoader] The coremod streams.core.StreamsCoreMod does not have a MCVersion annotation, it may cause issues with this version of Minecraft
2015-02-15 13:58:51 [FINE] [ForgeModLoader] Enqueued coremod StreamsCoreMod
2015-02-15 13:58:51 [FINE] [ForgeModLoader] Examining for coremod candidacy Thaumcraft-1.7.10-4.2.3.4.jar
2015-02-15 13:58:51 [FINEST] [ForgeModLoader] Found FMLCorePluginContainsFMLMod marker in Thaumcraft-1.7.10-4.2.3.4.jar, it will be examined later for regular @Mod instances
2015-02-15 13:58:51 [FINE] [ForgeModLoader] Instantiating coremod class DepLoader
2015-02-15 13:58:51 [WARNING] [ForgeModLoader] The coremod thaumcraft.codechicken.core.launch.DepLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
2015-02-15 13:58:51 [FINE] [ForgeModLoader] Enqueued coremod DepLoader
2015-02-15 13:58:51 [FINE] [ForgeModLoader] Examining for coremod candidacy ThaumicTinkerer-2.5-1.7.10-162.jar
2015-02-15 13:58:51 [FINEST] [ForgeModLoader] Found FMLCorePluginContainsFMLMod marker in ThaumicTinkerer-2.5-1.7.10-162.jar, it will be examined later for regular @Mod instances
2015-02-15 13:58:51 [FINE] [ForgeModLoader] Instantiating coremod class ThaumicTLoaderContainer
2015-02-15 13:58:51 [INFO] [STDERR] java.lang.NoClassDefFoundError: org/apache/logging/log4j/LogManager
2015-02-15 13:58:51 [INFO] [STDERR] 	at thaumic.tinkerer.preloader.ThaumicTLoaderContainer.<clinit>(ThaumicTLoaderContainer.java:19)
2015-02-15 13:58:51 [INFO] [STDERR] 	at java.lang.Class.forName0(Native Method)
2015-02-15 13:58:51 [INFO] [STDERR] 	at java.lang.Class.forName(Class.java:249)
2015-02-15 13:58:51 [INFO] [STDERR] 	at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:386)
2015-02-15 13:58:51 [INFO] [STDERR] 	at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:310)
2015-02-15 13:58:51 [INFO] [STDERR] 	at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:212)
2015-02-15 13:58:51 [INFO] [STDERR] 	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90)
2015-02-15 13:58:51 [INFO] [STDERR] 	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67)
2015-02-15 13:58:51 [INFO] [STDERR] 	at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34)
2015-02-15 13:58:51 [INFO] [STDERR] 	at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:124)
2015-02-15 13:58:51 [INFO] [STDERR] 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:111)
2015-02-15 13:58:51 [INFO] [STDERR] 	at net.minecraft.launchwrapper.Launch.main(Launch.java:27)
2015-02-15 13:58:51 [INFO] [STDERR] Caused by: java.lang.ClassNotFoundException: org.apache.logging.log4j.LogManager
2015-02-15 13:58:51 [INFO] [STDERR] 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:186)
2015-02-15 13:58:51 [INFO] [STDERR] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
2015-02-15 13:58:51 [INFO] [STDERR] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
2015-02-15 13:58:51 [INFO] [STDERR] 	... 12 more
2015-02-15 13:58:51 [INFO] [STDERR] Caused by: java.lang.NullPointerException
2015-02-15 13:58:51 [INFO] [STDERR] 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:178)
2015-02-15 13:58:51 [INFO] [STDERR] 	... 14 more
2015-02-15 13:58:51 [SEVERE] [ForgeModLoader] An error occurred trying to configure the minecraft home at /Users/helenclark/Library/Application Support/minecraft for Forge Mod Loader
java.lang.NoClassDefFoundError: org/apache/logging/log4j/LogManager
	at thaumic.tinkerer.preloader.ThaumicTLoaderContainer.<clinit>(ThaumicTLoaderContainer.java:19)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:249)
	at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:386)
	at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:310)
	at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:212)
	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90)
	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67)
	at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34)
	at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:124)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:111)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:27)
Caused by: java.lang.ClassNotFoundException: org.apache.logging.log4j.LogManager
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:186)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	... 12 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:178)
	... 14 more
2015-02-15 13:58:51 [INFO] [STDERR] Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/logging/log4j/LogManager
2015-02-15 13:58:51 [INFO] [STDERR] 	at thaumic.tinkerer.preloader.ThaumicTLoaderContainer.<clinit>(ThaumicTLoaderContainer.java:19)
2015-02-15 13:58:51 [INFO] [STDERR] 	at java.lang.Class.forName0(Native Method)
2015-02-15 13:58:51 [INFO] [STDERR] 	at java.lang.Class.forName(Class.java:249)
2015-02-15 13:58:51 [INFO] [STDERR] 	at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:386)
2015-02-15 13:58:51 [INFO] [STDERR] 	at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:310)
2015-02-15 13:58:51 [INFO] [STDERR] 	at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:212)
2015-02-15 13:58:51 [INFO] [STDERR] 	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90)
2015-02-15 13:58:51 [INFO] [STDERR] 	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67)
2015-02-15 13:58:51 [INFO] [STDERR] 	at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34)
2015-02-15 13:58:51 [INFO] [STDERR] 	at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:124)
2015-02-15 13:58:51 [INFO] [STDERR] 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:111)
2015-02-15 13:58:51 [INFO] [STDERR] 	at net.minecraft.launchwrapper.Launch.main(Launch.java:27)
2015-02-15 13:58:51 [INFO] [STDERR] Caused by: java.lang.ClassNotFoundException: org.apache.logging.log4j.LogManager
2015-02-15 13:58:51 [INFO] [STDERR] 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:186)
2015-02-15 13:58:51 [INFO] [STDERR] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
2015-02-15 13:58:51 [INFO] [STDERR] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
2015-02-15 13:58:51 [INFO] [STDERR] 	... 12 more
2015-02-15 13:58:51 [INFO] [STDERR] Caused by: java.lang.NullPointerException
2015-02-15 13:58:51 [INFO] [STDERR] 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:178)
2015-02-15 13:58:51 [INFO] [STDERR] 	... 14 more

**Comment by Spartan322** [comment]
I don't think Minecraft 1.6.4 is supported, please update to fix. Also update your java, #67 will help. Also please a paste site like http://gist.github.com next time and provide the link.

**Comment by 1231chorosso** [comment]
same results on 1.7 with java 7

**Comment by Spartan322** [comment]
then give us the crash logs for Minecraft 1.7 on java 7, please use http://gits.github.com and give us the link.

**Comment by Spartan322** [comment]
also I don't know if the mods being used are supported by CSM.

**Comment by Spartan322** [comment]
Might want to close this as invalid and need logs.

**Comment by SanAndreasP** [comment]
Will do in 4 days, then we have full 2 weeks

**Comment by CliffracerX** [comment]
Missing logs, presumably the whole Java 6/7 issue with macs.  Again.
