### ISSUE TITLE
Mac crash, with java 8

### ISSUE THREAD

**Issue by sovied** [SanAndreasP/ClaySoldiersMod#80]
Logs below

[22:58:58] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[22:58:58] [main/INFO] [LaunchWrapper]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[22:58:58] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
[22:58:58] [main/INFO] [FML]: Forge Mod Loader version 7.10.85.1291 for Minecraft 1.7.10 loading
[22:58:58] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.6.0_65, running on Mac OS X:x86_64:10.7.5, installed at /System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home
[22:58:58] [main/WARN] [FML]: The coremod codechicken.nei.asm.NEICorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[22:58:58] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:461]: java.lang.NoClassDefFoundError: codechicken/lib/asm/ASMInit
[22:58:58] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at codechicken.nei.asm.NEICorePlugin.<init>(NEICorePlugin.java:18)
[22:58:58] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[22:58:58] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
[22:58:58] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
[22:58:58] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
[22:58:58] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.lang.Class.newInstance0(Class.java:357)
[22:58:58] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.lang.Class.newInstance(Class.java:310)
[22:58:58] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:458)
[22:58:58] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:346)
[22:58:58] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:214)
[22:58:58] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90)
[22:58:58] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67)
[22:58:58] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34)
[22:58:58] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126)
[22:58:58] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[22:58:58] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[22:58:58] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:488]: Caused by: java.lang.ClassNotFoundException: codechicken.lib.asm.ASMInit
[22:58:58] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[22:58:58] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
[22:58:58] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
[22:58:58] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:492]: 	... 16 more
[22:58:58] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:488]: Caused by: java.lang.NullPointerException
[22:58:58] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
[22:58:58] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:492]: 	... 18 more
[22:58:58] [main/ERROR] [FML]: An error occurred trying to configure the minecraft home at /Users/shereealmeida/Library/Application Support/minecraft for Forge Mod Loader
java.lang.NoClassDefFoundError: codechicken/lib/asm/ASMInit
	at codechicken.nei.asm.NEICorePlugin.<init>(NEICorePlugin.java:18) ~[NotEnoughItems-1.7.10-1.0.3.74-universal.jar:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.6.0_65]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39) ~[?:1.6.0_65]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27) ~[?:1.6.0_65]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513) ~[?:1.6.0_65]
	at java.lang.Class.newInstance0(Class.java:357) ~[?:1.6.0_65]
	at java.lang.Class.newInstance(Class.java:310) ~[?:1.6.0_65]
	at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:458) ~[forge-1.7.10-10.13.2.1291.jar:?]
	at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:346) ~[forge-1.7.10-10.13.2.1291.jar:?]
	at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:214) ~[forge-1.7.10-10.13.2.1291.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90) [forge-1.7.10-10.13.2.1291.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67) [forge-1.7.10-10.13.2.1291.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34) [forge-1.7.10-10.13.2.1291.jar:?]
	at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126) [forge-1.7.10-10.13.2.1291.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
Caused by: java.lang.ClassNotFoundException: codechicken.lib.asm.ASMInit
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306) ~[?:1.6.0_65]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247) ~[?:1.6.0_65]
	... 16 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306) ~[?:1.6.0_65]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247) ~[?:1.6.0_65]
	... 16 more
Exception in thread "main" [22:58:58] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:461]: java.lang.NoClassDefFoundError: codechicken/lib/asm/ASMInit
[22:58:58] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at codechicken.nei.asm.NEICorePlugin.<init>(NEICorePlugin.java:18)
[22:58:58] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[22:58:58] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
[22:58:58] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
[22:58:58] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
[22:58:58] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.lang.Class.newInstance0(Class.java:357)
[22:58:58] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.lang.Class.newInstance(Class.java:310)
[22:58:58] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:458)
[22:58:58] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:346)
[22:58:58] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:214)
[22:58:58] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90)
[22:58:58] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67)
[22:58:58] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34)
[22:58:58] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126)
[22:58:58] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[22:58:58] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[22:58:58] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:488]: Caused by: java.lang.ClassNotFoundException: codechicken.lib.asm.ASMInit
[22:58:58] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[22:58:58] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
[22:58:58] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
[22:58:58] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:492]: 	... 16 more
[22:58:58] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:488]: Caused by: java.lang.NullPointerException
[22:58:58] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:490]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
[22:58:58] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTraceAsCause:492]: 	... 18 more

**Comment by Spartan322** [comment]
#67 this says you are using java 6, Mac forces that, please look at the issue I referenced.

**Comment by Spartan322** [comment]
Odd, this says you are using JDK 6 (which shouldn't work, but does seem to be an issue) but it appears this issue is caused by another mod, though you might want to checkout #67 because this crash log says you haven't set up java 7/8 properly.

**Comment by CliffracerX** [comment]
"Java is Java HotSpot(TM) 64-Bit Server VM, version 1.6.0_65, running on Mac OS X:x86_64:10.7.5, installed at "
Your Minecraft isn't using java 8.  Take a look at the other issues of this type.

**Comment by SanAndreasP** [comment]
Looks more like yoiu don't have CodeChickenLib installed. Either way it's not a CSM issue.
