### ISSUE TITLE
manager pack keeps crashing

### ISSUE THREAD

**Issue by stan1234** [SanAndreasP/ClaySoldiersMod#93]
the pack keeps crashing i don't know what the problem is heres the report
[21:50:37] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[21:50:37] [main/INFO] [LaunchWrapper]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[21:50:37] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
[21:50:37] [main/INFO] [FML]: Forge Mod Loader version 7.99.4.1408 for Minecraft 1.7.10 loading
[21:50:37] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.6.0_65, running on Mac OS X:x86_64:10.8.5, installed at /System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home
[21:50:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:461]: java.lang.UnsupportedClassVersionError: de/sanandrew/core/manpack/init/ManPackLoadingPlugin : Unsupported major.minor version 51.0
[21:50:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.lang.ClassLoader.defineClass1(Native Method)
[21:50:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
[21:50:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
[21:50:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
[21:50:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
[21:50:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
[21:50:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
[21:50:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.security.AccessController.doPrivileged(Native Method)
[21:50:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
[21:50:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117)
[21:50:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
[21:50:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
[21:50:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.lang.Class.forName0(Native Method)
[21:50:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.lang.Class.forName(Class.java:249)
[21:50:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:417)
[21:50:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:346)
[21:50:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:214)
[21:50:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90)
[21:50:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67)
[21:50:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34)
[21:50:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126)
[21:50:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[21:50:37] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[21:50:37] [main/ERROR] [FML]: An error occurred trying to configure the minecraft home at /Users/AbdullaAhmed/Library/Application Support/minecraft for Forge Mod Loader
java.lang.UnsupportedClassVersionError: de/sanandrew/core/manpack/init/ManPackLoadingPlugin : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.6.0_65]
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637) ~[?:1.6.0_65]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621) ~[?:1.6.0_65]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141) ~[?:1.6.0_65]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283) ~[?:1.6.0_65]
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58) ~[?:1.6.0_65]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197) ~[?:1.6.0_65]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.6.0_65]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190) ~[?:1.6.0_65]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306) ~[?:1.6.0_65]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247) ~[?:1.6.0_65]
	at java.lang.Class.forName0(Native Method) ~[?:1.6.0_65]
	at java.lang.Class.forName(Class.java:249) ~[?:1.6.0_65]
	at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:417) ~[forge-1.7.10-10.13.3.1408-1.7.10.jar:?]
	at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:346) ~[forge-1.7.10-10.13.3.1408-1.7.10.jar:?]
	at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:214) ~[forge-1.7.10-10.13.3.1408-1.7.10.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90) [forge-1.7.10-10.13.3.1408-1.7.10.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67) [forge-1.7.10-10.13.3.1408-1.7.10.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34) [forge-1.7.10-10.13.3.1408-1.7.10.jar:?]
	at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126) [forge-1.7.10-10.13.3.1408-1.7.10.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
Exception in thread "main" [21:50:38] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:461]: java.lang.UnsupportedClassVersionError: de/sanandrew/core/manpack/init/ManPackLoadingPlugin : Unsupported major.minor version 51.0
[21:50:38] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.lang.ClassLoader.defineClass1(Native Method)
[21:50:38] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
[21:50:38] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
[21:50:38] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
[21:50:38] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
[21:50:38] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
[21:50:38] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
[21:50:38] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.security.AccessController.doPrivileged(Native Method)
[21:50:38] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
[21:50:38] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117)
[21:50:38] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
[21:50:38] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
[21:50:38] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.lang.Class.forName0(Native Method)
[21:50:38] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.lang.Class.forName(Class.java:249)
[21:50:38] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:417)
[21:50:38] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:346)
[21:50:38] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:214)
[21:50:38] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90)
[21:50:38] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67)
[21:50:38] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34)
[21:50:38] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126)
[21:50:38] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[21:50:38] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Spartan322** [comment]
#67

**Comment by stan1234** [comment]
i already have java 7 update 79

**Comment by Spartan322** [comment]
You may have it, but minecraft isn't using it, cause Mac forces 1.6 (if you read your crash log, it says that, its only few lines from the top) look at it #67 for better explaination

**Comment by SanAndreasP** [comment]
What @Spartan322 said.

**Comment by stan1234** [comment]
Ok I fixed it thanks
