### ISSUE TITLE
Mod just crashes when opening Minecraft

### ISSUE THREAD

**Issue by PotasiumBear** [SanAndreasP/ClaySoldiersMod#94]
Here is the report
---- Minecraft Crash Report ----
// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 31/05/15 12:17
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: de/sanandrew/core/manpack/util/SAPUtils
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:162)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:515)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:239)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: de/sanandrew/core/manpack/util/SAPUtils
	at de.sanandrew.mods.claysoldiers.util.RegistryItems.initialize(RegistryItems.java:69)
	at de.sanandrew.mods.claysoldiers.util.ClaySoldiersMod.modPreInit(ClaySoldiersMod.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:513)
	... 10 more
Caused by: java.lang.ClassNotFoundException: de.sanandrew.core.manpack.util.SAPUtils
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 38 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 40 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 412006656 bytes (392 MB) / 925036544 bytes (882 MB) up to 2134114304 bytes (2035 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 Optifine OptiFine_1.7.10_HD_B6 31 mods loaded, 31 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	FML{7.10.85.1291} [Forge Mod Loader] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized
	Forge{10.13.2.1291} [Minecraft Forge] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized
	CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	NotEnoughItems{1.0.4.94} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.4.94-universal.jar) Unloaded->Constructed->Pre-initialized
	sapmanpack{2.2.0} [SanAndreasPs Manager Pack CORE edition] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	DamageIndicatorsMod{3.2.3} [Damage Indicators] ([1.7.10]DamageIndicatorsMod-3.2.3.jar) Unloaded->Constructed->Pre-initialized
	deconstruction{2.2.5} [The Deconstruction Mod] ([MC1.7.10]deconstruction[v2.2.5].jar) Unloaded->Constructed->Pre-initialized
	AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10-1.2.4.jar) Unloaded->Constructed->Pre-initialized
	candycraftmod{(Alpha)} [CandyCraft] (CandyCraft-1.2.3 (1.7.10).jar) Unloaded->Constructed->Pre-initialized
	claysoldiers{2.0.0b} [Clay Soldiers Mod] (ClaySoldiersMod-1.7.10-2.0.0b.jar) Unloaded->Constructed->Errored
	customnpcs{1.7.10b} [CustomNpcs] (CustomNPCs_1.7.10b.jar) Unloaded->Constructed->Pre-initialized
	props{2.0.2} [Decocraft] (Decocraft-2.0.2_1.7.10.jar) Unloaded->Constructed->Pre-initialized
	ElementalCreepers{4.2.4} [Elemental Creepers] (Elemental Creepers-universal_1.7.10-4.2.4.jar) Unloaded->Constructed->Pre-initialized
	ExtrabiomesXL{3.16.2} [ExtrabiomesXL] (extrabiomesxl_1.7.10-3.16.2.jar) Unloaded->Constructed->Pre-initialized
	flansmod{4.8.0} [Flan's Mod] (Flans Mod-1.7.10-4.8.0.jar) Unloaded->Constructed->Pre-initialized
	ganyssurface{1.11.1} [Gany's Surface] (Ganys Surface-1.11.1.jar) Unloaded->Constructed->Pre-initialized
	iChunUtil{4.2.2} [iChunUtil] (iChunUtil-4.2.2.jar) Unloaded->Constructed->Pre-initialized
	GraviGun{4.0.0-beta} [GraviGun] (GravityGun-4.0.0-beta.jar) Unloaded->Constructed->Pre-initialized
	GrimoireOfGaia{1.0.0} [Grimoire of Gaia 3] (GrimoireOfGaia3-1.7.10-1.0.9.jar) Unloaded->Constructed->Pre-initialized
	journeymap{5.0.1} [JourneyMap] (JourneyMap5.0.1_Unlimited_MC1.7.10.jar) Unloaded->Constructed->Pre-initialized
	Morph{0.9.1} [Morph] (Morphing-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized
	harvestcraft{1.7.10g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10h.jar) Unloaded->Constructed->Pre-initialized
	PortalGun{4.0.0-beta-4} [PortalGun] (PortalGun-4.0.0-beta-4.jar) Unloaded->Constructed->Pre-initialized
	secretroomsmod{4.7.1} [The SecretRoomsMod] (secretroomsmod-1.7.10-4.7.1.394.jar) Unloaded->Constructed->Pre-initialized
	TF2Dispenser{1.7.10} [TF2 Dispenser] (TF2Dispenser-1.7.10.jar) Unloaded->Constructed->Pre-initialized
	TF2Sentry{1.7.10} [TF2 Sentry] (TF2Sentry-1.7.10.jar) Unloaded->Constructed->Pre-initialized
	TF2Teleporter{1.7.10} [TF2 Teleporter] (TF2Teleporter-1.7.10.jar) Unloaded->Constructed->Pre-initialized
	tgp{1.0} [The Great Pigoku Mod] (TheGreatPigokuMod v1.1(1.7.10).jar) Unloaded->Constructed->Pre-initialized
	TwilightForest{2.3.7} [The Twilight Forest] (twilightforest-1.7.10-2.3.7.jar) Unloaded->Constructed->Pre-initialized
	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) Unloaded->Constructed->Pre-initialized

**Comment by Spartan322** [comment]
Install the SAPManagerPack, please check rules before posting issues.

**Comment by SanAndreasP** [comment]
Install the latest Manager Pack (2.5.0), you're way outdated (2.2.0)!
